#ifndef SG_BUILD_CONTAINERS_H
#define SG_BUILD_CONTAINERS_H

#include <SG_DLL.h>

#ifdef SG_BUILDING_CONTAINERS
    #define SG_CONTAINERS_DLL SG_DLL_EXPORT
#else
    #define SG_CONTAINERS_DLL SG_DLL_IMPORT
#endif

#endif // SG_BUILD_CONTAINERS_H
