name: Android AAB Clang build
description: Builds a fully self contained SGEXTN app for Android AAB using Clang compiler. SGEXTN libraries, Qt libraries, and C++ libraries are packaged with the application executable. The produced AAB will be ready for distribution on Google Play after being signed and contains all 4 Android ABIs. This action should be run on a ubuntu-latest GitHub Actions runner.

inputs:
  app-name:
    required: true
    description: name of your application executable, example my-application
    type: string
  app-version:
    required: true
    description: version number of your application, example 1.0.0
    type: string
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string
  cmake-target-name:
    required: true
    description: name of CMake target for your application executable, this is used to locate the executable, the executable will be renamed after that
    type: string

runs:
  using: "composite"
  steps:
    - name: pull repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
        ref: ${{github.ref}}

    - name: install Ninja
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: install Qt for Android ARM64
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_arm64_v8a

    - name: install Qt for Android ARM32
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_armv7

    - name: install Qt for Android AMD64
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_x86_64

    - name: install Qt for Android AMD32
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_x86

    - name: install Android SDK & NDK
      uses: android-actions/setup-android@v3
      with:
        packages: platform-tools platforms;android-28 build-tools;36.0.0 ndk;27.2.12479018
        log-accepted-android-sdk-licenses: false

    - name: install Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: delete unnecessary Qt plugins
      shell: bash
      run: |
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/printsupport"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/printsupport"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/printsupport"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/printsupport"

    - name: build SGEXTN
      shell: bash
      run: |
        cd ..
        git clone https://github.com/InfinityIntegral/SGEXTN.git
        cd SGEXTN
        mkdir build
        cd build
        ../../Qt/${{inputs.qt-version}}/android_arm64_v8a/bin/qt-cmake -DQT_ANDROID_BUILD_ALL_ABIS=TRUE -DANDROID_SDK_ROOT=/usr/local/lib/android/sdk -DANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.2.12479018 -S .. -B . -GNinja -DCMAKE_BUILD_TYPE=Release -DANDROID_PLATFORM=android-28 --log-level=VERBOSE
        cmake --build . --config Release --target aab --verbose -- -j1
        cd ..
        cmake --install build --config Release --prefix ../SGEXTN_install/ARM64
        cmake --install build/android_abi_builds/armeabi-v7a --config Release --prefix ../SGEXTN_install/ARM32
        cmake --install build/android_abi_builds/x86_64 --config Release --prefix ../SGEXTN_install/AMD64
        cmake --install build/android_abi_builds/x86 --config Release --prefix ../SGEXTN_install/AMD32
        echo "" > ${{github.workspace}}/request_arm64

    - name: build application binary
      shell: bash
      run: |
        sed -i '/find_package(SGEXTN REQUIRED)/c\
        if(EXISTS "${CMAKE_SOURCE_DIR}/request_arm64")\
            include(${{github.workspace}}/../SGEXTN_install/ARM64/lib/cmake/SGEXTN/SGEXTNConfig.cmake)\
            file(REMOVE "${CMAKE_SOURCE_DIR}/request_arm64")\
            file(WRITE "${CMAKE_SOURCE_DIR}/request_amd64" "")\
            message(STATUS "requested and found ARM64 SGEXTN pre built")\
        elseif(EXISTS "${CMAKE_SOURCE_DIR}/request_arm32")\
            include(${{github.workspace}}/../SGEXTN_install/ARM32/lib/cmake/SGEXTN/SGEXTNConfig.cmake)\
            file(REMOVE "${CMAKE_SOURCE_DIR}/request_arm32")\
            message(STATUS "requested and found ARM32 SGEXTN pre built")\
        elseif(EXISTS "${CMAKE_SOURCE_DIR}/request_amd64")\
            include(${{github.workspace}}/../SGEXTN_install/AMD64/lib/cmake/SGEXTN/SGEXTNConfig.cmake)\
            file(REMOVE "${CMAKE_SOURCE_DIR}/request_amd64")\
            file(WRITE "${CMAKE_SOURCE_DIR}/request_amd32" "")\
            message(STATUS "requested and found AMD64 SGEXTN pre built")\
        elseif(EXISTS "${CMAKE_SOURCE_DIR}/request_amd32")\
            include(${{github.workspace}}/../SGEXTN_install/AMD32/lib/cmake/SGEXTN/SGEXTNConfig.cmake)\
            file(REMOVE "${CMAKE_SOURCE_DIR}/request_amd32")\
            file(WRITE "${CMAKE_SOURCE_DIR}/request_arm32" "")\
            message(STATUS "requested and found AMD32 SGEXTN pre built")\
        else()\
            message(FATAL_ERROR "no ABI found?")\
        endif()' CMakeLists.txt
        ls .
        mkdir build
        cd build
        ../../Qt/${{inputs.qt-version}}/android_arm64_v8a/bin/qt-cmake -DQT_ANDROID_BUILD_ALL_ABIS=TRUE -DANDROID_SDK_ROOT=/usr/local/lib/android/sdk -DANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.2.12479018 -S .. -B . -GNinja -DCMAKE_BUILD_TYPE=Release -DANDROID_PLATFORM=android-28 --log-level=VERBOSE
        cmake --build . --config Release --target aab --verbose -- -j1

    - name: delete QML tooling
      shell: bash
      run: |
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmltooling"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/qmltooling"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/qmltooling"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/qmltooling"

    - name: package app
      shell: bash
      run: |
        mkdir -p ${{inputs.app-name}}
        cp build/android-build/build/outputs/bundle/release/android-build-release.aab ${{inputs.app-name}}/${{inputs.app-name}}.aab

    - name: write version file
      shell: bash
      run: |
        echo "" > ${{inputs.app-name}}/version.txt
        echo "using Qt version ${{inputs.qt-version}}" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang --version | head -n1)
        echo "using ARM64 Android compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi28-clang --version | head -n1)
        echo "using ARM32 Android compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android28-clang --version | head -n1)
        echo "using AMD64 Android compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android28-clang --version | head -n1)
        echo "using AMD32 Android compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        echo "building application ${{inputs.app-name}} version ${{inputs.app-version}}" >> ${{inputs.app-name}}/version.txt

    - name: upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-clang-${{inputs.app-name}}-${{inputs.app-version}}-build
        path: build

    - name: upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-clang-${{inputs.app-name}}-${{inputs.app-version}}-binary
        path: ${{inputs.app-name}}

    - name: log info
      if: always()
      shell: bash
      run: |
        unzip build/android-build/build/outputs/bundle/release/android-build-release.aab -d aab
        echo "logging information -------------------"
        echo ""
        echo "version information:"
        cat ${{inputs.app-name}}/version.txt
        echo ""
        echo "packaged executables and libraries for ARM64:"
        ls aab/base/lib/arm64-v8a
        echo "packaged executables and libraries for ARM32:"
        ls aab/base/lib/armeabi-v7a
        echo "packaged executables and libraries for AMD64:"
        ls aab/base/lib/x86_64
        echo "packaged executables and libraries for AMD32:"
        ls aab/base/lib/x86
