name: Android AAB Clang build
description: Builds a fully self contained SGEXTN app for Android AAB using Clang compiler. SGEXTN libraries, Qt libraries, and C++ libraries are packaged with the application executable. The produced AAB will be ready for distribution on Google Play after being signed and contains all 4 Android ABIs. This action should be run on a ubuntu-latest GitHub Actions runner.

inputs:
  app-name:
    required: true
    description: name of your application executable, example my-application
    type: string
  app-version:
    required: true
    description: version number of your application, example 1.0.0
    type: string
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string
  sgextn-version:
    required: true
    description: version of SGEXTN to use, it is preferred that this matches the SGEXTN version you have on your development machine, example 6.2.0
    type: string
  cmake-target-name:
    required: true
    description: name of CMake target for your application executable, this is used to locate the executable, the executable will be renamed after that
    type: string
  user-facing-app-name:
    required: true
    description: application name as how you want the user to see it, this does not need to be a valid file name, example My Application
    type: string
  user-facing-app-version:
    required: true
    description: application version as how you want the user to see it, this does not need to be numerical, example version 1.0.0
    type: string
  app-icon:
    required: true
    description: location of the application icon PNG image as a path in your GitHub repository, example resources/icon.png
    type: string
  user-facing-organisation-name:
    required: true
    description: your organisation name as how you want the user to see it, example 05524F.sg
    type: string
  bundle-id:
    required: true
    description: application bundle identifier, only used on MacOS, iOS, and Android, must be a reverse URL style dot separated list, with every entry containing only lowercase letters and numbers and must start with a lowercase letter, example sg.singapore05524f.myapplication
    type: string
  app-category:
    required: true
    description: one from the list AudioVideo, Audio, Video, Development, Education, Game, Graphics, Network, Office, Science, Settings, System, Utility, only used on Linux, example Utility
    type: string
  licensing:
    required: true
    description: software licensing for your application, you are strongly recommended to use General Public License version 3 (GPLv3), the license file from your GitHub repository will always be copied regardless of this input, example GPLv3
    type: string
  license-file:
    required: true
    description: path to the license file in your GitHub repository, typically LICENSE.txt, example LICENSE.txt
    type: string
  app-description:
    required: true
    description: a short explanatory note to the user what the app is about
    type: string

runs:
  using: "composite"
  steps:
    - name: pull repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
        ref: ${{github.ref}}

    - name: install Ninja
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: install Qt for Android ARM64
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_arm64_v8a

    - name: install Qt for Android ARM32
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_armv7

    - name: install Qt for Android AMD64
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_x86_64

    - name: install Qt for Android AMD32
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_x86

    - name: install Android SDK & NDK
      uses: android-actions/setup-android@v3
      with:
        packages: platform-tools platforms;android-28 build-tools;36.0.0 ndk;27.2.12479018
        log-accepted-android-sdk-licenses: false

    - name: install Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: install ImageMagick
      shell: bash
      run: |
        sudo apt update
        sudo apt install imagemagick

    - name: delete unnecessary Qt plugins
      shell: bash
      run: |
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/printsupport"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/printsupport"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/printsupport"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/printsupport"

    - name: build SGEXTN
      shell: bash
      run: |
        cd ..
        git clone --depth 1 --branch v${{inputs.sgextn-version}} https://github.com/InfinityIntegral/SGEXTN.git
        cd SGEXTN
        cp -a ../Qt/${{inputs.qt-version}}/android_arm64_v8a/src/android/templates android
        mkdir -p android/res/mipmap-ldpi
        mkdir -p android/res/mipmap-mdpi
        mkdir -p android/res/mipmap-hdpi
        mkdir -p android/res/mipmap-xhdpi
        mkdir -p android/res/mipmap-xxhdpi
        mkdir -p android/res/mipmap-xxxhdpi
        convert -size 1x1 xc:none android/res/mipmap-ldpi/icon.png
        convert -size 1x1 xc:none android/res/mipmap-mdpi/icon.png
        convert -size 1x1 xc:none android/res/mipmap-hdpi/icon.png
        convert -size 1x1 xc:none android/res/mipmap-xhdpi/icon.png
        convert -size 1x1 xc:none android/res/mipmap-xxhdpi/icon.png
        convert -size 1x1 xc:none android/res/mipmap-xxxhdpi/icon.png
        mkdir build
        cd build
        ../../Qt/${{inputs.qt-version}}/android_arm64_v8a/bin/qt-cmake -DQT_ANDROID_BUILD_ALL_ABIS=TRUE -DANDROID_SDK_ROOT=/usr/local/lib/android/sdk -DANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.2.12479018 -S .. -B . -GNinja -DCMAKE_BUILD_TYPE=Release -DANDROID_PLATFORM=android-28
        cmake --build . --config Release --target aab -- -j1
        cd ..
        cmake --install build --config Release --prefix ../SGEXTN_install/ARM64
        cmake --install build/android_abi_builds/armeabi-v7a --config Release --prefix ../SGEXTN_install/ARM32
        cmake --install build/android_abi_builds/x86_64 --config Release --prefix ../SGEXTN_install/AMD64
        cmake --install build/android_abi_builds/x86 --config Release --prefix ../SGEXTN_install/AMD32
        echo "" > ${{github.workspace}}/request_arm64

    - name: copy over everything
      shell: bash
      run: |
        cp -a ../Qt/${{inputs.qt-version}}/android_arm64_v8a/src/android/templates android
        mkdir -p android/assets
        cp "../SGEXTN/LICENSE.txt" "android/assets/SGEXTN_LICENSE.txt"
        [ -e "${{inputs.license-file}}" ] && cp "${{inputs.license-file}}" "android/assets/LICENSE.txt"
        [ -e README.md ] && cp README.md "android/assets/info.md"
        echo -e "This app is built and packaged using SGEXTN automated GitHub Actions workflows\nFor more information, see info.md if it exists" > "android/assets/README.txt"

    - name: generate app icons
      shell: bash
      run: |
        mkdir -p android/res/mipmap-ldpi
        mkdir -p android/res/mipmap-mdpi
        mkdir -p android/res/mipmap-hdpi
        mkdir -p android/res/mipmap-xhdpi
        mkdir -p android/res/mipmap-xxhdpi
        mkdir -p android/res/mipmap-xxxhdpi
        mkdir -p icons
        cp "${{inputs.app-icon}}" "icons/original.png"
        w=$(identify -format "%w" icons/original.png)
        h=$(identify -format "%h" icons/original.png)
        size=$(( w>h ? w : h ))
        convert icons/original.png -background "rgba(1,1,1,0)" -gravity center -extent ${size}x${size} icons/square.png
        convert icons/square.png -resize 36x36 android/res/mipmap-ldpi/icon.png
        convert icons/square.png -resize 48x48 android/res/mipmap-mdpi/icon.png
        convert icons/square.png -resize 72x72 android/res/mipmap-hdpi/icon.png
        convert icons/square.png -resize 96x96 android/res/mipmap-xhdpi/icon.png
        convert icons/square.png -resize 144x144 android/res/mipmap-xxhdpi/icon.png
        convert icons/square.png -resize 192x192 android/res/mipmap-xxxhdpi/icon.png

    - name: build application binary
      shell: bash
      run: |
        sed -i '/find_package(SGEXTN REQUIRED)/c\
        if(EXISTS "${CMAKE_SOURCE_DIR}/request_arm64")\
            include(${{github.workspace}}/../SGEXTN_install/ARM64/lib/cmake/SGEXTN/SGEXTNConfig.cmake)\
            file(REMOVE "${CMAKE_SOURCE_DIR}/request_arm64")\
            file(WRITE "${CMAKE_SOURCE_DIR}/request_amd64" "")\
            message(STATUS "requested and found ARM64 SGEXTN pre built")\
        elseif(EXISTS "${CMAKE_SOURCE_DIR}/request_arm32")\
            include(${{github.workspace}}/../SGEXTN_install/ARM32/lib/cmake/SGEXTN/SGEXTNConfig.cmake)\
            file(REMOVE "${CMAKE_SOURCE_DIR}/request_arm32")\
            message(STATUS "requested and found ARM32 SGEXTN pre built")\
        elseif(EXISTS "${CMAKE_SOURCE_DIR}/request_amd64")\
            include(${{github.workspace}}/../SGEXTN_install/AMD64/lib/cmake/SGEXTN/SGEXTNConfig.cmake)\
            file(REMOVE "${CMAKE_SOURCE_DIR}/request_amd64")\
            file(WRITE "${CMAKE_SOURCE_DIR}/request_amd32" "")\
            message(STATUS "requested and found AMD64 SGEXTN pre built")\
        elseif(EXISTS "${CMAKE_SOURCE_DIR}/request_amd32")\
            include(${{github.workspace}}/../SGEXTN_install/AMD32/lib/cmake/SGEXTN/SGEXTNConfig.cmake)\
            file(REMOVE "${CMAKE_SOURCE_DIR}/request_amd32")\
            file(WRITE "${CMAKE_SOURCE_DIR}/request_arm32" "")\
            message(STATUS "requested and found AMD32 SGEXTN pre built")\
        endif()' CMakeLists.txt
        VERSION=${{inputs.app-version}}
        read MAJOR MINOR PATCH <<< $(echo "$VERSION" | tr '.' ' ')
        [[ $MINOR -lt 10 ]] && MINOR="0$MINOR"
        [[ $PATCH -lt 10 ]] && PATCH="0$PATCH"
        VERSION_CODE="${MAJOR}${MINOR}${PATCH}"
        mkdir build
        cd build
        ../../Qt/${{inputs.qt-version}}/android_arm64_v8a/bin/qt-cmake -DQT_ANDROID_BUILD_ALL_ABIS=TRUE -DANDROID_SDK_ROOT=/usr/local/lib/android/sdk -DANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.2.12479018 -S .. -B . -GNinja -DCMAKE_BUILD_TYPE=Release -DANDROID_PLATFORM=android-28 -DSGEXTN_ANDROID_BUNDLE_ID="${{inputs.bundle-id}}" -DSGEXTN_ANDROID_USER_FACING_APP_NAME="${{inputs.user-facing-app-name}}" -DSGEXTN_ANDROID_APP_VERSION=$VERSION_CODE -DSGEXTN_ANDROID_USER_FACING_APP_VERSION="${{inputs.user-facing-app-version}}"
        cmake --build . --config Release --target aab -- -j1

    - name: delete QML tooling
      shell: bash
      run: |
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmltooling"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_armv7/plugins/qmltooling"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86_64/plugins/qmltooling"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_x86/plugins/qmltooling"

    - name: package app
      shell: bash
      run: |
        mkdir -p ${{inputs.app-name}}
        cp build/android-build/build/outputs/bundle/release/android-build-release.aab ${{inputs.app-name}}/${{inputs.app-name}}.aab

    - name: write version file
      shell: bash
      run: |
        echo "" > ${{inputs.app-name}}/version.txt
        echo "using Qt version ${{inputs.qt-version}}" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang --version | head -n1)
        echo "using ARM64 Android compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi28-clang --version | head -n1)
        echo "using ARM32 Android compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android28-clang --version | head -n1)
        echo "using AMD64 Android compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android28-clang --version | head -n1)
        echo "using AMD32 Android compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        echo "building application ${{inputs.app-name}} version ${{inputs.app-version}}" >> ${{inputs.app-name}}/version.txt

    - name: upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-clang-${{inputs.app-name}}-${{inputs.app-version}}-build
        path: build

    - name: upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-clang-${{inputs.app-name}}-${{inputs.app-version}}-binary
        path: ${{inputs.app-name}}

    - name: log info
      if: always()
      shell: bash
      run: |
        unzip build/android-build/build/outputs/bundle/release/android-build-release.aab -d aab
        echo "logging information -------------------"
        echo ""
        echo "version information:"
        cat ${{inputs.app-name}}/version.txt
        echo ""
        echo "packaged executables and libraries for ARM64:"
        ls aab/base/lib/arm64-v8a
        echo "packaged executables and libraries for ARM32:"
        ls aab/base/lib/armeabi-v7a
        echo "packaged executables and libraries for AMD64:"
        ls aab/base/lib/x86_64
        echo "packaged executables and libraries for AMD32:"
        ls aab/base/lib/x86
