name: Pull source code
description: Retrieves Qt and SGEXTN source code from respective GitHub repositories. The versions used correspond to whatever was used by this GitHub Actions workflow run to build the apps. The zip files qt-source-code and sgextn-source-code must be made available to users of your application for LGPL compliance purposes. This action should be run on a ubuntu-latest GitHub Actions runner.

inputs:
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string

runs:
  using: "composite"
  steps:
    - name: pull everything
      shell: bash
      run: |
        git clone --depth 1 https://github.com/InfinityIntegral/SGEXTN.git
        rm -rf SGEXTN/.git
        mkdir -p Qt
        cd Qt
        git clone --depth 1 --branch v${{inputs.qt-version}} https://github.com/qt/qtbase.git
        git clone --depth 1 --branch v${{inputs.qt-version}} https://github.com/qt/qtdeclarative.git
        git clone --depth 1 --branch v${{inputs.qt-version}} https://github.com/qt/qtsvg.git
        git clone --depth 1 --branch v${{inputs.qt-version}} https://github.com/qt/qttools.git
        git clone --depth 1 --branch v${{inputs.qt-version}} https://github.com/qt/qttranslations.git
        git clone --depth 1 --branch v${{inputs.qt-version}} https://github.com/qt/qtwayland.git
        git clone --depth 1 --branch v${{inputs.qt-version}} https://github.com/qt/qtshadertools.git
        rm -rf qtbase/.git
        rm -rf qtdeclarative/.git
        rm -rf qtsvg/.git
        rm -rf qttools/.git
        rm -rf qttranslations/.git
        rm -rf qtwayland/.git
        rm -rf qtshadertools/.git

    - name: upload SGEXTN
      uses: actions/upload-artifact@v4
      with:
        name: sgextn-source-code
        path: SGEXTN

    - name: upload Qt
      uses: actions/upload-artifact@v4
      with:
        name: qt-source-code
        path: Qt
