name: Windows ARM MSVC build
description: Builds a fully self contained SGEXTN app for Windows ARM64 using MSVC compiler. SGEXTN libraries, Qt libraries, and C++ libraries are packaged with the application executable. This action should be run on a windows-11-arm GitHub Actions runner.

inputs:
  app-name:
    required: true
    description: name of your application executable, example my-application
    type: string
  app-version:
    required: true
    description: version number of your application, example 1.0.0
    type: string
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string
  sgextn-version:
    required: true
    description: version of SGEXTN to use, it is preferred that this matches the SGEXTN version you have on your development machine, example 6.2.0
    type: string
  cmake-target-name:
    required: true
    description: name of CMake target for your application executable, this is used to locate the executable, the executable will be renamed after that
    type: string
  user-facing-app-name:
    required: true
    description: application name as how you want the user to see it, this does not need to be a valid file name, example My Application
    type: string
  user-facing-app-version:
    required: true
    description: application version as how you want the user to see it, this does not need to be numerical, example version 1.0.0
    type: string
  app-icon:
    required: true
    description: location of the application icon PNG image as a path in your GitHub repository, example resources/icon.png
    type: string
  user-facing-organisation-name:
    required: true
    description: your organisation name as how you want the user to see it, example 05524F.sg
    type: string
  bundle-id:
    required: true
    description: application bundle identifier, only used on MacOS, iOS, and Android, must be a reverse URL style dot separated list, with every entry containing only lowercase letters and numbers and must start with a lowercase letter, example sg.singapore05524f.myapplication
    type: string
  app-category:
    required: true
    description: one from the list AudioVideo, Audio, Video, Development, Education, Game, Graphics, Network, Office, Science, Settings, System, Utility, only used on Linux, example Utility
    type: string
  licensing:
    required: true
    description: software licensing for your application, you are strongly recommended to use General Public License version 3 (GPLv3), the license file from your GitHub repository will always be copied regardless of this input, example GPLv3
    type: string
  license-file:
    required: true
    description: path to the license file in your GitHub repository, typically LICENSE.txt, example LICENSE.txt
    type: string
  app-description:
    required: true
    description: a short explanatory note to the user what the app is about
    type: string

runs:
  using: "composite"
  steps:
    - name: pull repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
        ref: ${{github.ref}}

    - name: install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: windows_arm64
        target: desktop
        dir: ${{github.workspace}}\..
        cache: true
        modules: qtshadertools
        tools: 'tools_vcredist,qt.tools.vcredist_msvc2022_arm64 tools_cmake tools_ninja'

    - name: delete unnecessary Qt plugins
      shell: pwsh
      run: |
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_arm64\plugins\designer"
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_arm64\plugins\help"
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_arm64\plugins\sqldrivers"

    - name: build SGEXTN
      shell: cmd
      run: |
        cd ..
        git clone --depth 1 --branch v${{inputs.sgextn-version}} https://github.com/InfinityIntegral/SGEXTN.git
        cd SGEXTN
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsarm64.bat"
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        cd ..
        cmake --install build --config Release --prefix ../SGEXTN_install

    - name: build application binary
      shell: cmd
      run: |
        set PATH=${{github.workspace}}\..\SGEXTN_install\lib;${{github.workspace}}\..\SGEXTN_install\lib\cmake\SGEXTN;%PATH%
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsarm64.bat"
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: delete QML tooling
      shell: pwsh
      run: |
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_arm64\plugins\qmllint"
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_arm64\plugins\qmlls"
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_arm64\plugins\qmltooling"

    - name: package app using windowsdeployqt
      shell: pwsh
      run: |
        mkdir ${{github.workspace}}\${{inputs.app-name}}
        Copy-Item -Path "build\${{inputs.cmake-target-name}}.exe" -Destination "${{github.workspace}}\${{inputs.app-name}}\${{inputs.app-name}}.exe"
        Get-ChildItem -Path ..\SGEXTN\build -Filter *.dll -Recurse | ForEach-Object {Copy-Item $_.FullName -Destination ${{github.workspace}}\${{inputs.app-name}} -Force}
        Get-ChildItem -Path build -Filter *.dll -Recurse | ForEach-Object {Copy-Item $_.FullName -Destination ${{github.workspace}}\${{inputs.app-name}} -Force}
        & "..\Qt\${{inputs.qt-version}}\msvc2022_arm64\bin\windeployqt.exe" ${{github.workspace}}\${{inputs.app-name}}\${{inputs.app-name}}.exe -qmldir=${{github.workspace}}\..\SGEXTN\SG_Widgets\assets --no-translations --no-compiler-runtime --release
        Copy-Item "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\14.44.35112\x64\Microsoft.VC143.CRT\*" ${{inputs.app-name}} -Recurse -Force

    - name: write version file
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsarm64.bat"
        echo. > "${{inputs.app-name}}\version.txt"
        echo using Qt version ${{inputs.qt-version}} >> "${{inputs.app-name}}\version.txt"
        for /f "delims=" %%i in ('cl 2^>^&1 ^| findstr /R /C:".*"') do (
            echo using compiler %%i >> "${{inputs.app-name}}\version.txt"
            goto donecompiler
        )
        :donecompiler
        echo building application ${{inputs.app-name}} version ${{inputs.app-version}} >> "${{inputs.app-name}}\version.txt"

    - name: install rcedit
      shell: pwsh
      run: |
        choco install rcedit -y

    - name: generate icon file
      shell: pwsh
      run: |
        mkdir icons
        cp "${{inputs.app-icon}}" "icons\original.png"
        cd icons
        $env:MAGICK_CODER_MODULE_PATH="C:\Program Files (x86)\ImageMagick-7.1.2-Q16-HDRI\modules\coders"
        magick original.png -background "rgba(1,1,1,0)" -gravity center -extent "%[fx:max(w,h)]x%[fx:max(w,h)]" square.png
        magick square.png -resize 16x16 16.png
        magick square.png -resize 24x24 24.png
        magick square.png -resize 32x32 32.png
        magick square.png -resize 48x48 48.png
        magick square.png -resize 256x256 256.png
        magick 16.png 24.png 32.png 48.png 256.png icon.ico

    - name: write metadata
      shell: pwsh
      run: |
        rcedit.exe "${{inputs.app-name}}\${{inputs.app-name}}.exe" --set-icon "icons\icon.ico" --set-version-string "ProductName" "${{inputs.user-facing-app-name}}" --set-version-string "FileVersion" "${{inputs.user-facing-app-version}}" --set-version-string "CompanyName" "${{inputs.user-facing-organisation-name}}" --set-version-string "FileDescription" "${{inputs.app-description}}" --set-version-string "LegalCopyright" "${{inputs.licensing}}"

    - name: copy README and license
      shell: pwsh
      run: |
        cp "..\SGEXTN\LICENSE.txt" "${{inputs.app-name}}\SGEXTN_LICENSE.txt"
        cp "${{inputs.license-file}}" "${{inputs.app-name}}\LICENSE.txt" -ErrorAction SilentlyContinue
        cp README.md "${{inputs.app-name}}\info.md" -ErrorAction SilentlyContinue
        echo "This app is built and packaged using SGEXTN automated GitHub Actions workflows`nFor more information, see info.md if it exists`nRun install.vbs to install the application properly`nRun uninstall.vbs to uninstall the application and delete it from your computer`nOnce the app is installed, do not move it in the file system" > "${{inputs.app-name}}\README.txt"

    - name: create install and uninstall scripts
      shell: pwsh
      run: |
        echo @"
        Option Explicit
        Dim objShell, objFSO
        Dim strAppPath, strDesktop, strStartMenu
        Set objShell = CreateObject("WScript.Shell")
        Set objFSO = CreateObject("Scripting.FileSystemObject")
        strAppPath = objFSO.GetAbsolutePathName(".") & "\${{inputs.app-name}}.exe"
        strDesktop = objShell.SpecialFolders("Desktop") & "\${{inputs.user-facing-app-name}}.lnk"
        strStartMenu = objShell.SpecialFolders("StartMenu") & "\Programs\${{inputs.user-facing-app-name}}.lnk"
        Call CreateShortcut(strDesktop, strAppPath)
        Call CreateShortcut(strStartMenu, strAppPath)
        Sub CreateShortcut(targetPath, appPath)
        Dim sc
        Set sc = objShell.CreateShortcut(targetPath)
        sc.TargetPath = appPath
        sc.WorkingDirectory = objFSO.GetParentFolderName(appPath)
        sc.Save
        End Sub
        "@ | Set-Content "${{inputs.app-name}}\install.vbs"
        echo @"
        Option Explicit
        Dim objShell, objFSO
        Dim strDesktop, strStartMenu
        Set objShell = CreateObject("WScript.Shell")
        Set objFSO = CreateObject("Scripting.FileSystemObject")
        strDesktop = objShell.SpecialFolders("Desktop") & "\${{inputs.user-facing-app-name}}.lnk"
        strStartMenu = objShell.SpecialFolders("StartMenu") & "\Programs\${{inputs.user-facing-app-name}}.lnk"
        If objFSO.FileExists(strDesktop) Then objFSO.DeleteFile strDesktop, True
        If objFSO.FileExists(strStartMenu) Then objFSO.DeleteFile strStartMenu, True
        On Error Resume Next
        objFSO.DeleteFolder objFSO.GetParentFolderName(WScript.ScriptFullName), True
        On Error GoTo 0
        "@ | Set-Content "${{inputs.app-name}}\uninstall.vbs"

    - name: upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: windows-arm-msvc-${{inputs.app-name}}-${{inputs.app-version}}-build
        path: build

    - name: upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: windows-arm-msvc-${{inputs.app-name}}-${{inputs.app-version}}-binary
        path: ${{inputs.app-name}}

    - name: log info
      if: always()
      shell: pwsh
      run: |
        echo "logging information -------------------"
        echo ""
        echo "version information:"
        cat ${{inputs.app-name}}\version.txt
        echo ""
        echo "packaged executables and libraries:"
        ls ${{inputs.app-name}}
