name: iOS Clang build
description: Builds a fully self contained SGEXTN app for iOS using Apple Clang compiler. SGEXTN libraries and Qt libraries are packaged with the application executable. The C++ libraries are guaranteed to exist on any reasonably new device. The application is not signed and must be signed and packaged into a .ipa manually before distribution. This action should be run on a macos-latest GitHub Actions runner.

inputs:
  app-name:
    required: true
    description: name of your application executable, example my-application
    type: string
  app-version:
    required: true
    description: version number of your application, example 1.0.0
    type: string
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string
  cmake-target-name:
    required: true
    description: name of CMake target for your application executable, this is used to locate the executable, the executable will be renamed after that
    type: string

runs:
  using: "composite"
  steps:
    - name: pull repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
        ref: ${{github.ref}}

    - name: install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: mac
        target: ios
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools

    - name: delete unnecessary Qt plugins
      shell: bash
      run: |
        rm -rf ../Qt/${{inputs.qt-version}}/ios/plugins/designer
        rm -rf ../Qt/${{inputs.qt-version}}/ios/plugins/help
        rm -rf ../Qt/${{inputs.qt-version}}/ios/plugins/printsupport

    - name: build SGEXTN
      shell: bash
      run: |
        cd ..
        git clone https://github.com/InfinityIntegral/SGEXTN.git
        cd SGEXTN
        mkdir build
        cd build
        ../../Qt/${{inputs.qt-version}}/ios/bin/qt-cmake .. -DCMAKE_BUILD_TYPE=Release
        xcodebuild -list -project SGEXTN.xcodeproj
        xcodebuild build -project SGEXTN.xcodeproj -scheme SGEXTN -configuration Release -destination "generic/platform=iOS" -destination-timeout 1 ENABLE_ONLY_ACTIVE_RESOURCES=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -sdk iphoneos
        cd ..
        cmake --install build --config Release --prefix ../SGEXTN_install

    - name: build application binary
      shell: bash
      run: |
        export PATH="${{github.workspace}}/../SGEXTN_install/lib:${{github.workspace}}/../SGEXTN_install/lib/cmake/SGEXTN:$PATH"
        mkdir build
        cd build
        ../../Qt/${{inputs.qt-version}}/ios/bin/qt-cmake .. -DCMAKE_BUILD_TYPE=Release
        xcodebuild build -project ${{inputs.app-name}}.xcodeproj -scheme ${{inputs.app-name}} -configuration Release -destination "generic/platform=iOS" -destination-timeout 1 ENABLE_ONLY_ACTIVE_RESOURCES=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -sdk iphoneos

    - name: delete QML tooling
      shell: bash
      run: |
        rm -rf ../Qt/${{inputs.qt-version}}/ios/plugins/qmllint
        rm -rf ../Qt/${{inputs.qt-version}}/ios/plugins/qmlls
        rm -rf ../Qt/${{inputs.qt-version}}/ios/plugins/qmltooling
        rm -rf ../Qt/${{inputs.qt-version}}/ios/plugins/sqldrivers

    - name: package app using macdeployqt
      shell: bash
      run: |
        mkdir -p ${{inputs.app-name}}
        cp -a build/${{inputs.cmake-target-name}}.app ${{inputs.app-name}}/${{inputs.app-name}}.app

    - name: write version file
      shell: bash
      run: |
        echo "" > ${{inputs.app-name}}/version.txt
        echo "using Qt version ${{inputs.qt-version}}" >> ${{inputs.app-name}}/version.txt
        echo "using compiler $(clang --version | head -n1)" >> ${{inputs.app-name}}/version.txt
        echo "building application ${{inputs.app-name}} version ${{inputs.app-version}}" >> ${{inputs.app-name}}/version.txt

    - name: upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-clang-${{inputs.app-name}}-${{inputs.app-version}}-build
        path: build

    - name: upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-clang-${{inputs.app-name}}-${{inputs.app-version}}-binary
        path: ${{inputs.app-name}}

    - name: log info
      if: always()
      shell: bash
      run: |
        echo "logging information -------------------"
        echo ""
        echo "version information:"
        cat ${{inputs.app-name}}/version.txt
        echo ""
        echo "packaged executable and other stuff in root folder:"
        ls ${{inputs.app-name}}/${{inputs.app-name}}.app
        echo ""
        echo "packaged libraries:"
        ls ${{inputs.app-name}}/${{inputs.app-name}}.app/Frameworks
