name: Android ARM64 Clang build
description: Builds a fully self contained SGEXTN app for Android ARM64 using Clang compiler. SGEXTN libraries, Qt libraries, and C++ libraries are packaged with the application executable. This action should be run on a ubuntu-latest GitHub Actions runner.

inputs:
  app-name:
    required: true
    description: name of your application executable, example my-application
    type: string
  app-version:
    required: true
    description: version number of your application, example 1.0.0
    type: string
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string
  cmake-target-name:
    required: true
    description: name of CMake target for your application executable, this is used to locate the executable, the executable will be renamed after that
    type: string
  user-facing-app-name:
    required: true
    description: application name as how you want the user to see it, this does not need to be a valid file name, example My Application
    type: string
  user-facing-app-version:
    required: true
    description: application version as how you want the user to see it, this does not need to be numerical, example version 1.0.0
    type: string
  app-icon:
    required: true
    description: location of the application icon PNG image as a path in your GitHub repository, example resources/icon.png
    type: string
  user-facing-organisation-name:
    required: true
    description: your organisation name as how you want the user to see it, example 05524F.sg
    type: string
  bundle-id:
    required: true
    description: application bundle identifier, only used on MacOS, iOS, and Android, must be a reverse URL style dot separated list, with every entry containing only lowercase letters and numbers and must start with a lowercase letter, example sg.singapore05524f.myapplication
    type: string
  app-category:
    required: true
    description: one from the list AudioVideo, Audio, Video, Development, Education, Game, Graphics, Network, Office, Science, Settings, System, Utility, only used on Linux, example Utility
    type: string
  licensing:
    required: true
    description: software licensing for your application, you are strongly recommended to use General Public License version 3 (GPLv3), the license file from your GitHub repository will always be copied regardless of this input, example GPLv3
    type: string
  license-file:
    required: true
    description: path to the license file in your GitHub repository, typically LICENSE.txt, example LICENSE.txt
    type: string
  app-description:
    required: true
    description: a short explanatory note to the user what the app is about
    type: string

runs:
  using: "composite"
  steps:
    - name: pull repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
        ref: ${{github.ref}}

    - name: install Ninja
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: android
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        arch: android_arm64_v8a

    - name: install Android SDK & NDK
      uses: android-actions/setup-android@v3
      with:
        packages: platform-tools platforms;android-28 build-tools;36.0.0 ndk;27.2.12479018
        log-accepted-android-sdk-licenses: false

    - name: install Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: delete unnecessary Qt plugins
      shell: bash
      run: |
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/designer"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/help"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/sqldrivers"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/printsupport"

    - name: build SGEXTN
      shell: bash
      run: |
        cd ..
        git clone https://github.com/InfinityIntegral/SGEXTN.git
        cd SGEXTN
        cp -a ../Qt/${{inputs.qt-version}}/android_arm64_v8a/src/android/templates android
        mkdir build
        cd build
        cmake .. -G "Ninja" -DANDROID_SDK_ROOT=/usr/local/lib/android/sdk -DANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.2.12479018 -DANDROID_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/27.2.12479018/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-28
        cmake --build . --config Release
        cd ..
        cmake --install build --config Release --prefix ../SGEXTN_install

    - name: copy over everything
      shell: bash
      run: |
        cp -a ../Qt/${{inputs.qt-version}}/android_arm64_v8a/src/android/templates android
        mkdir -p android/assets
        [ -e "${{inputs.license-file}}" ] && cp "${{inputs.license-file}}" "android/assets/LICENSE.txt"
        [ -e README.md ] && cp README.md "android/assets/info.md"
        echo -e "This app is built and packaged using SGEXTN automated GitHub Actions workflows\nFor more information, see info.md if it exists" > "android/assets/README.txt"

    - name: install ImageMagick
      shell: bash
      run: |
        sudo apt update
        sudo apt install imagemagick

    - name: generate app icons
      shell: bash
      run: |
        mkdir -p android/res/drawable-ldpi
        mkdir -p android/res/drawable-mdpi
        mkdir -p android/res/drawable-hdpi
        mkdir -p android/res/drawable-xhdpi
        mkdir -p android/res/drawable-xxhdpi
        mkdir -p android/res/drawable-xxxhdpi
        mkdir -p icons
        cp "${{inputs.app-icon}}" "icons/original.png"
        w=$(identify -format "%w" icons/original.png)
        h=$(identify -format "%h" icons/original.png)
        size=$(( w>h ? w : h ))
        convert icons/original.png -background "rgba(1,1,1,0)" -gravity center -extent ${size}x${size} icons/square.png
        convert icons/square.png -resize 36x36 android/res/drawable-ldpi/icon.png
        convert icons/square.png -resize 48x48 android/res/drawable-mdpi/icon.png
        convert icons/square.png -resize 72x72 android/res/drawable-hdpi/icon.png
        convert icons/square.png -resize 96x96 android/res/drawable-xhdpi/icon.png
        convert icons/square.png -resize 144x144 android/res/drawable-xxhdpi/icon.png
        convert icons/square.png -resize 192x192 android/res/drawable-xxxhdpi/icon.png

    - name: build application binary
      shell: bash
      run: |
        export PATH="${{github.workspace}}/../SGEXTN_install/lib:${{github.workspace}}/../SGEXTN_install/lib/cmake/SGEXTN:$PATH"
        VERSION=${{inputs.app-version}}
        read MAJOR MINOR PATCH <<< $(echo "$VERSION" | tr '.' ' ')
        [[ $MINOR -lt 10 ]] && MINOR="0$MINOR"
        [[ $PATCH -lt 10 ]] && PATCH="0$PATCH"
        VERSION_CODE="${MAJOR}${MINOR}${PATCH}"
        mkdir build
        cd build
        cmake .. -G "Ninja" -DANDROID_SDK_ROOT=/usr/local/lib/android/sdk -DANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.2.12479018 -DANDROID_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/27.2.12479018/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-28 -DSGEXTN_ANDROID_BUNDLE_ID="${{inputs.bundle-id}}" -DSGEXTN_ANDROID_USER_FACING_APP_NAME="${{inputs.user-facing-app-name}}" -DSGEXTN_ANDROID_APP_VERSION=$VERSION_CODE -DSGEXTN_ANDROID_USER_FACING_APP_VERSION="${{inputs.user-facing-app-version}}"
        cmake --build . --config Release

    - name: delete QML tooling
      shell: bash
      run: |
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmllint"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmlls"
        rm -rf "../Qt/${{inputs.qt-version}}/android_arm64_v8a/plugins/qmltooling"

    - name: package app
      shell: bash
      run: |
        mkdir -p ${{inputs.app-name}}
        cp build/android-build/${{inputs.cmake-target-name}}.apk ${{inputs.app-name}}/${{inputs.app-name}}.apk
        $JAVA_HOME/bin/keytool -genkeypair -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=SGEXTN debug key,O=SGEXTN_Debug,C=SG"
        /usr/local/lib/android/sdk/build-tools/36.0.0/apksigner sign --ks debug.keystore --ks-pass pass:android ${{inputs.app-name}}/${{inputs.app-name}}.apk
        /usr/local/lib/android/sdk/build-tools/36.0.0/apksigner verify ${{inputs.app-name}}/${{inputs.app-name}}.apk

    - name: write version file
      shell: bash
      run: |
        echo "" > ${{inputs.app-name}}/version.txt
        echo "using Qt version ${{inputs.qt-version}}" >> ${{inputs.app-name}}/version.txt
        compilerVersion=$(/usr/local/lib/android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang --version | head -n1)
        echo "using compiler $compilerVersion" >> ${{inputs.app-name}}/version.txt
        echo "building application ${{inputs.app-name}} version ${{inputs.app-version}}" >> ${{inputs.app-name}}/version.txt

    - name: upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-arm64-clang-${{inputs.app-name}}-${{inputs.app-version}}-build
        path: build

    - name: upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-arm64-clang-${{inputs.app-name}}-${{inputs.app-version}}-binary
        path: ${{inputs.app-name}}

    - name: log info
      if: always()
      shell: bash
      run: |
        unzip build/android-build/${{inputs.cmake-target-name}}.apk -d apk
        echo "logging information -------------------"
        echo ""
        echo "version information:"
        cat ${{inputs.app-name}}/version.txt
        echo ""
        echo "packaged executables and libraries:"
        ls apk/lib/arm64-v8a
