name: MacOS Clang build
description: Builds a fully self contained SGEXTN app for MacOS compatible with both Intel and Apple Silicon using Apple Clang compiler. SGEXTN libraries and Qt libraries are packaged with the application executable. The C++ libraries are guaranteed to exist on any reasonably new Mac. This action should be run on a macos-latest GitHub Actions runner.

inputs:
  app-name:
    required: true
    description: name of your application executable, example my-application
    type: string
  app-version:
    required: true
    description: version number of your application, example 1.0.0
    type: string
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string
  cmake-target-name:
    required: true
    description: name of CMake target for your application executable, this is used to locate the executable, the executable will be renamed after that
    type: string

runs:
  using: "composite"
  steps:
    - name: pull repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
        ref: ${{github.ref}}

    - name: install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: mac
        target: desktop
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        tools: 'tools_cmake tools_ninja'

    - name: delete unnecessary Qt plugins
      shell: bash
      run: |
        rm -rf ../Qt/${{inputs.qt-version}}/macos/plugins/designer
        rm -rf ../Qt/${{inputs.qt-version}}/macos/plugins/help
        rm -rf ../Qt/${{inputs.qt-version}}/macos/plugins/sqldrivers
        rm -rf ../Qt/${{inputs.qt-version}}/macos/plugins/printsupport

    - name: build SGEXTN
      shell: bash
      run: |
        cd ..
        git clone https://github.com/InfinityIntegral/SGEXTN.git
        cd SGEXTN
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_SYSTEM_NAME=Darwin ..
        cmake --build . --config Release
        cd ..
        cmake --install build --config Release --prefix ../SGEXTN_install

    - name: build application binary
      shell: bash
      run: |
        export PATH="${{github.workspace}}/../SGEXTN_install/lib:${{github.workspace}}/../SGEXTN_install/lib/cmake/SGEXTN:$PATH"
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_SYSTEM_NAME=Darwin ..
        cmake --build . --config Release

    - name: delete QML tooling
      shell: bash
      run: |
        rm -rf ../Qt/${{inputs.qt-version}}/macos/plugins/qmllint
        rm -rf ../Qt/${{inputs.qt-version}}/macos/plugins/qmlls
        rm -rf ../Qt/${{inputs.qt-version}}/macos/plugins/qmltooling

    - name: package app using macdeployqt
      shell: bash
      run: |
        mkdir -p package/${{inputs.app-name}}.app/Contents/MacOS
        mkdir -p package/${{inputs.app-name}}.app/Contents/Frameworks
        cp "build/${{inputs.cmake-target-name}}" package/${{inputs.app-name}}.app/Contents/MacOS/${{inputs.app-name}}
        find ../SGEXTN/build -type f -name "*.dylib" -exec cp {} package/${{inputs.app-name}}.app/Contents/Frameworks/ \;
        find build -type f -name "*.dylib" -exec cp {} package/${{inputs.app-name}}.app/Contents/Frameworks/ \;
        ../Qt/${{inputs.qt-version}}/macos/bin/macdeployqt package/${{inputs.app-name}}.app -qmldir=${{github.workspace}}/../SGEXTN/SG_Widgets/assets
        mv package/${{inputs.app-name}}.app/Contents ${{inputs.app-name}}
        chmod +x ${{inputs.app-name}}/MacOS/${{inputs.app-name}}

    - name: write version file
      shell: bash
      run: |
        echo "" > ${{inputs.app-name}}/version.txt
        echo "using Qt version ${{inputs.qt-version}}" >> ${{inputs.app-name}}/version.txt
        echo "using compiler $(clang --version | head -n1)" >> ${{inputs.app-name}}/version.txt
        echo "building application ${{inputs.app-name}} version ${{inputs.app-version}}" >> ${{inputs.app-name}}/version.txt

    - name: upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: macos-clang-${{inputs.app-name}}-${{inputs.app-version}}-build
        path: build

    - name: upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: macos-clang-${{inputs.app-name}}-${{inputs.app-version}}-binary
        path: ${{inputs.app-name}}

    - name: log info
      if: always()
      shell: bash
      run: |
        echo "logging information -------------------"
        echo ""
        echo "version information:"
        cat ${{inputs.app-name}}/version.txt
        echo ""
        echo "packaged executables:"
        ls ${{inputs.app-name}}/MacOS
        echo ""
        echo "packaged libraries:"
        ls ${{inputs.app-name}}/Frameworks
