QT += core gui qml quick quickcontrols2 gui-private
QMAKE_CXXFLAGS_RELEASE += -O3 -flto -ffunction-sections -fdata-sections -std=c++20
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_DEBUG += -std=c++20
QMAKE_LFLAGS += -flto -Wl,--gc-sections
DISTFILES += .gitignore LICENSE.txt README.md \
    SGEXTN/RendererInterface/transparencyindicator/transparencyindicator.frag \
    SGEXTN/RendererInterface/transparencyindicator/transparencyindicator.vert \
    SGEXTN/colourpickerrendering/huechoice/huechoice.frag \
    SGEXTN/colourpickerrendering/huechoice/huechoice.vert \
    SGEXTN/colourpickerrendering/lightnesschoice/lightnesschoice.frag \
    SGEXTN/colourpickerrendering/lightnesschoice/lightnesschoice.vert \
    SGEXTN/colourpickerrendering/saturationchoice/saturationchoice.frag \
    SGEXTN/colourpickerrendering/saturationchoice/saturationchoice.vert \
    SGEXTN/colourpickerrendering/transparencychoice/transparencychoice.frag \
    SGEXTN/colourpickerrendering/transparencychoice/transparencychoice.vert
    
SOURCES += SGEXTN/misc/main.cpp \
    SGEXTN/RendererInterface/sgrbaserenderer.cpp \
    SGEXTN/RendererInterface/sgrbasesyncer.cpp \
    SGEXTN/RendererInterface/sgrcommandrequest.cpp \
    SGEXTN/RendererInterface/sgrdatabuffer.cpp \
    SGEXTN/RendererInterface/sgrelementbufferobject.cpp \
    SGEXTN/RendererInterface/sgrgraphicslanguagetype.cpp \
    SGEXTN/RendererInterface/sgrimage.cpp \
    SGEXTN/RendererInterface/sgrrenderergenerator.cpp \
    SGEXTN/RendererInterface/sgrrenderernode.cpp \
    SGEXTN/RendererInterface/sgrrendererwidget.cpp \
    SGEXTN/RendererInterface/sgrrenderingprogramme.cpp \
    SGEXTN/RendererInterface/sgrtexture.cpp \
    SGEXTN/RendererInterface/sgrvertexbufferobject.cpp \
    SGEXTN/RendererInterface/sgrvertexproperty.cpp \
    SGEXTN/RendererInterface/transparencyindicator/sgrtransparencyindicatorrenderer.cpp \
    SGEXTN/bypassquickui/sgxresizer.cpp \
    SGEXTN/bypassquickui/sgxthemecolours.cpp \
    SGEXTN/containers/sglcrash.cpp \
    SGEXTN/customisation/sgwcustomisationpagecontrol.cpp \
    SGEXTN/customisation/sgxfontsizecustomisation.cpp \
    SGEXTN/filesystem/sgxfile.cpp \
    SGEXTN/math/sglfloatconstants.cpp \
    SGEXTN/math/sglfloatlimits.cpp \
    SGEXTN/math/sglfloatmath.cpp \
    SGEXTN/math/sglintlimits.cpp \
    SGEXTN/math/sglintmath.cpp \
    SGEXTN/math/sgllonglonglimits.cpp \
    SGEXTN/math/sgllonglongmath.cpp \
    SGEXTN/primitives/sgxchar.cpp \
    SGEXTN/primitives/sgxstring.cpp \
    SGEXTN/quickui/sgrscreenshotcallback.cpp \
    SGEXTN/quickui/sgwwidgetquickinterface.cpp \
    SGEXTN/quickui/sgxsingcorrectquickinterface.cpp \
    SGEXTN/quickui/sgxtimerquickinterface.cpp \
    SGEXTN/rng/sgxrandomnumbergenerator.cpp \
    SGEXTN/template/sgwfontsizecustomisationpage.cpp \
    SGEXTN/widgets/instantiable/sgwmultitouchreceiver.cpp \
    SGEXTN/widgets/instantiable/sgwsingletouchreceiver.cpp \
    SGEXTN/SingCorrect/sgwsingcorrectcustomisationpage.cpp \
    SGEXTN/SingCorrect/sgxsingcorrectcore.cpp \
    SGEXTN/SingCorrect/sgxsingcorrectcustomisation.cpp \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicematerial.cpp \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicequickuielement.cpp \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicesgwidget.cpp \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoiceshader.cpp \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicematerial.cpp \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicequickuielement.cpp \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicesgwidget.cpp \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoiceshader.cpp \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicematerial.cpp \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicequickuielement.cpp \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicesgwidget.cpp \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoiceshader.cpp \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicematerial.cpp \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicequickuielement.cpp \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicesgwidget.cpp \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoiceshader.cpp \
    SGEXTN/customisation/sgxthemecolourscustomisation.cpp \
    SGEXTN/filesystem/sgxfilebinutilities.cpp \
    SGEXTN/filesystem/sgxfiledownloader.cpp \
    SGEXTN/filesystem/sgxfilesystem.cpp \
    SGEXTN/filesystem/sgxfileuploader.cpp \
    SGEXTN/misc/sgxcentral.cpp \
    SGEXTN/notifications/sgwnotify.cpp \
    SGEXTN/primitives/sgxcolourhsla.cpp \
    SGEXTN/primitives/sgxcolourrgba.cpp \
    SGEXTN/primitives/sgxidentifier.cpp \
    SGEXTN/primitives/sgxtimestamp.cpp \
    SGEXTN/primitives/sgxtouchevent.cpp \
    SGEXTN/primitives/sgxvector2.cpp \
    SGEXTN/quickui/sgxquickinterface.cpp \
    SGEXTN/quickui/sgxquickresizer.cpp \
    SGEXTN/quickui/sgxthemecoloursetting.cpp \
    SGEXTN/template/sgwcolourpicker.cpp \
    SGEXTN/template/sgwthemecustomisationpage.cpp \
    SGEXTN/timer/sgxtimer.cpp \
    SGEXTN/userDefinedClasses/sgucentralmanagement.cpp \
    SGEXTN/widgets/noninstantiable/sgwbackground.cpp \
    SGEXTN/widgets/instantiable/sgwblankwidget.cpp \
    SGEXTN/widgets/noninstantiable/sgwbutton.cpp \
    SGEXTN/widgets/instantiable/sgwcolourpickerwidget.cpp \
    SGEXTN/widgets/instantiable/sgwcustomrenderer.cpp \
    SGEXTN/widgets/enums/sgwdefaultfonts.cpp \
    SGEXTN/widgets/instantiable/sgwiconbutton.cpp \
    SGEXTN/widgets/instantiable/sgwiconlabel.cpp \
    SGEXTN/widgets/noninstantiable/sgwinput.cpp \
    SGEXTN/widgets/noninstantiable/sgwlabel.cpp \
    SGEXTN/widgets/instantiable/sgwlonginput.cpp \
    SGEXTN/widgets/instantiable/sgwlonglabel.cpp \
    SGEXTN/widgets/instantiable/sgwpagebackground.cpp \
    SGEXTN/widgets/unique/sgwparent.cpp \
    SGEXTN/widgets/unique/sgwroot.cpp \
    SGEXTN/widgets/instantiable/sgwscrollview.cpp \
    SGEXTN/widgets/instantiable/sgwsequentiallonglabel.cpp \
    SGEXTN/widgets/instantiable/sgwsequentialscrollview.cpp \
    SGEXTN/widgets/unique/sgwstatusbar.cpp \
    SGEXTN/widgets/instantiable/sgwtextbutton.cpp \
    SGEXTN/widgets/instantiable/sgwtextinput.cpp \
    SGEXTN/widgets/instantiable/sgwtextlabel.cpp \
    SGEXTN/widgets/enums/sgwtype.cpp \
    SGEXTN/widgets/noninstantiable/sgwwidget.cpp
RESOURCES += SGEXTN/assets.qrc
HEADERS += \
    SGEXTN/RendererInterface/sgrbaserenderer.h \
    SGEXTN/RendererInterface/sgrbasesyncer.h \
    SGEXTN/RendererInterface/sgrcommandrequest.h \
    SGEXTN/RendererInterface/sgrdatabuffer.h \
    SGEXTN/RendererInterface/sgrelementbufferobject.h \
    SGEXTN/RendererInterface/sgrgraphicslanguagetype.h \
    SGEXTN/RendererInterface/sgrimage.h \
    SGEXTN/RendererInterface/sgrrenderergenerator.h \
    SGEXTN/RendererInterface/sgrrenderernode.h \
    SGEXTN/RendererInterface/sgrrendererwidget.h \
    SGEXTN/RendererInterface/sgrrenderingprogramme.h \
    SGEXTN/RendererInterface/sgrtexture.h \
    SGEXTN/RendererInterface/sgrvertexbufferobject.h \
    SGEXTN/RendererInterface/sgrvertexproperty.h \
    SGEXTN/RendererInterface/transparencyindicator/sgrtransparencyindicatorrenderer.h \
    SGEXTN/bypassquickui/sgxresizer.h \
    SGEXTN/bypassquickui/sgxthemecolours.h \
    SGEXTN/containers/sglarray.h \
    SGEXTN/containers/sglcrash.h \
    SGEXTN/containers/sgldeque.h \
    SGEXTN/containers/sglequalsto.h \
    SGEXTN/containers/sglhash.h \
    SGEXTN/containers/sglhashalgorithm.h \
    SGEXTN/containers/sgllesserthan.h \
    SGEXTN/containers/sglmap.h \
    SGEXTN/containers/sglmorethan.h \
    SGEXTN/containers/sglmultiset.h \
    SGEXTN/containers/sglpair.h \
    SGEXTN/containers/sglpriorityqueue.h \
    SGEXTN/containers/sglqueue.h \
    SGEXTN/containers/sglset.h \
    SGEXTN/containers/sglsort.h \
    SGEXTN/containers/sglspan.h \
    SGEXTN/containers/sglstack.h \
    SGEXTN/containers/sgltuple3.h \
    SGEXTN/containers/sgltuple4.h \
    SGEXTN/containers/sgltuple5.h \
    SGEXTN/containers/sglunorderedmap.h \
    SGEXTN/containers/sglunorderedmultiset.h \
    SGEXTN/containers/sglunorderedset.h \
    SGEXTN/containers/sglvector.h \
    SGEXTN/customisation/sgwcustomisationpagecontrol.h \
    SGEXTN/customisation/sgxfontsizecustomisation.h \
    SGEXTN/filesystem/sgxfile.h \
    SGEXTN/math/sglfloatconstants.h \
    SGEXTN/math/sglfloatlimits.h \
    SGEXTN/math/sglfloatmath.h \
    SGEXTN/math/sglintlimits.h \
    SGEXTN/math/sglintmath.h \
    SGEXTN/math/sgllonglonglimits.h \
    SGEXTN/math/sgllonglongmath.h \
    SGEXTN/primitives/sgxchar.h \
    SGEXTN/primitives/sgxstring.h \
    SGEXTN/quickui/sgrscreenshotcallback.h \
    SGEXTN/quickui/sgwwidgetquickinterface.h \
    SGEXTN/quickui/sgxsingcorrectquickinterface.h \
    SGEXTN/quickui/sgxtimerquickinterface.h \
    SGEXTN/rng/sgxrandomnumbergenerator.h \
    SGEXTN/template/sgwfontsizecustomisationpage.h \
    SGEXTN/widgets/instantiable/sgwmultitouchreceiver.h \
    SGEXTN/widgets/instantiable/sgwsingletouchreceiver.h \
    SGEXTN/SingCorrect/sgwsingcorrectcustomisationpage.h \
    SGEXTN/SingCorrect/sgxsingcorrectcore.h \
    SGEXTN/SingCorrect/sgxsingcorrectcustomisation.h \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicematerial.h \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicequickuielement.h \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicesgwidget.h \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoiceshader.h \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicematerial.h \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicequickuielement.h \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicesgwidget.h \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoiceshader.h \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicematerial.h \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicequickuielement.h \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicesgwidget.h \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoiceshader.h \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicematerial.h \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicequickuielement.h \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicesgwidget.h \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoiceshader.h \
    SGEXTN/customisation/sgxthemecolourscustomisation.h \
    SGEXTN/filesystem/sgxfilebinutilities.h \
    SGEXTN/filesystem/sgxfiledownloader.h \
    SGEXTN/filesystem/sgxfilesystem.h \
    SGEXTN/filesystem/sgxfileuploader.h \
    SGEXTN/misc/sgxcentral.h \
    SGEXTN/notifications/sgwnotify.h \
    SGEXTN/primitives/sgxcolourhsla.h \
    SGEXTN/primitives/sgxcolourrgba.h \
    SGEXTN/primitives/sgxidentifier.h \
    SGEXTN/primitives/sgxtimestamp.h \
    SGEXTN/primitives/sgxtouchevent.h \
    SGEXTN/primitives/sgxvector2.h \
    SGEXTN/quickui/sgxquickinterface.h \
    SGEXTN/quickui/sgxquickresizer.h \
    SGEXTN/quickui/sgxthemecoloursetting.h \
    SGEXTN/template/sgwcolourpicker.h \
    SGEXTN/template/sgwthemecustomisationpage.h \
    SGEXTN/timer/sgxtimer.h \
    SGEXTN/userDefinedClasses/sgucentralmanagement.h \
    SGEXTN/widgets/noninstantiable/sgwbackground.h \
    SGEXTN/widgets/instantiable/sgwblankwidget.h \
    SGEXTN/widgets/noninstantiable/sgwbutton.h \
    SGEXTN/widgets/instantiable/sgwcolourpickerwidget.h \
    SGEXTN/widgets/instantiable/sgwcustomrenderer.h \
    SGEXTN/widgets/enums/sgwdefaultfonts.h \
    SGEXTN/widgets/enums/sgwhorizontalalignment.h \
    SGEXTN/widgets/instantiable/sgwiconbutton.h \
    SGEXTN/widgets/instantiable/sgwiconlabel.h \
    SGEXTN/widgets/noninstantiable/sgwinput.h \
    SGEXTN/widgets/noninstantiable/sgwlabel.h \
    SGEXTN/widgets/instantiable/sgwlonginput.h \
    SGEXTN/widgets/instantiable/sgwlonglabel.h \
    SGEXTN/widgets/instantiable/sgwpagebackground.h \
    SGEXTN/widgets/unique/sgwparent.h \
    SGEXTN/widgets/unique/sgwroot.h \
    SGEXTN/widgets/instantiable/sgwscrollview.h \
    SGEXTN/widgets/instantiable/sgwsequentiallonglabel.h \
    SGEXTN/widgets/instantiable/sgwsequentialscrollview.h \
    SGEXTN/widgets/unique/sgwstatusbar.h \
    SGEXTN/widgets/instantiable/sgwtextbutton.h \
    SGEXTN/widgets/instantiable/sgwtextinput.h \
    SGEXTN/widgets/instantiable/sgwtextlabel.h \
    SGEXTN/widgets/enums/sgwtype.h \
    SGEXTN/widgets/enums/sgwverticalalignment.h \
    SGEXTN/widgets/noninstantiable/sgwwidget.h
