QT += core gui qml quick quickcontrols2
QMAKE_CXXFLAGS_RELEASE += -O3 -flto -ffunction-sections -fdata-sections -std=c++20
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_DEBUG += -std=c++20
QMAKE_LFLAGS += -flto -Wl,--gc-sections
DISTFILES += .gitignore LICENSE.txt README.md \
    SGEXTN/colourbackground/colourbackground.frag \
    SGEXTN/colourbackground/colourbackground.vert \
    SGEXTN/colourpickerrendering/huechoice/huechoice.frag \
    SGEXTN/colourpickerrendering/huechoice/huechoice.vert \
    SGEXTN/colourpickerrendering/lightnesschoice/lightnesschoice.frag \
    SGEXTN/colourpickerrendering/lightnesschoice/lightnesschoice.vert \
    SGEXTN/colourpickerrendering/saturationchoice/saturationchoice.frag \
    SGEXTN/colourpickerrendering/saturationchoice/saturationchoice.vert \
    SGEXTN/colourpickerrendering/transparencychoice/transparencychoice.frag \
    SGEXTN/colourpickerrendering/transparencychoice/transparencychoice.vert \
    SGEXTN/filesystem/bin.sgfile \
    SGEXTN/filesystem/singzip.sgfile \
    compilecommands.txt
SOURCES += SGEXTN/misc/main.cpp \
    $$PWD/bypassquickui/sgxresizer.cpp \
    $$PWD/bypassquickui/sgxthemecolours.cpp \
    $$PWD/containers/sglcrash.cpp \
    $$PWD/filesystem/sgxfile.cpp \
    $$PWD/primitives/sgxchar.cpp \
    $$PWD/primitives/sgxstring.cpp \
    $$PWD/quickui/sgwwidgetquickinterface.cpp \
    $$PWD/quickui/sgxsingcorrectquickinterface.cpp \
    $$PWD/quickui/sgxtimerquickinterface.cpp \
    SGEXTN/SingCorrect/sgwsingcorrectcustomisationpage.cpp \
    SGEXTN/SingCorrect/sgxsingcorrectcore.cpp \
    SGEXTN/SingCorrect/sgxsingcorrectcustomisation.cpp \
    SGEXTN/colourbackground/sgxrendercolourbackgroundmaterial.cpp \
    SGEXTN/colourbackground/sgxrendercolourbackgroundquickuielement.cpp \
    SGEXTN/colourbackground/sgxrendercolourbackgroundsgwidget.cpp \
    SGEXTN/colourbackground/sgxrendercolourbackgroundshader.cpp \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicematerial.cpp \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicequickuielement.cpp \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicesgwidget.cpp \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoiceshader.cpp \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicematerial.cpp \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicequickuielement.cpp \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicesgwidget.cpp \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoiceshader.cpp \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicematerial.cpp \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicequickuielement.cpp \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicesgwidget.cpp \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoiceshader.cpp \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicematerial.cpp \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicequickuielement.cpp \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicesgwidget.cpp \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoiceshader.cpp \
    SGEXTN/customisation/sgxthemecolourscustomisation.cpp \
    SGEXTN/filesystem/sgxfilebinutilities.cpp \
    SGEXTN/filesystem/sgxfiledownloader.cpp \
    SGEXTN/filesystem/sgxfilesystem.cpp \
    SGEXTN/filesystem/sgxfileuploader.cpp \
    SGEXTN/misc/sgxcentral.cpp \
    SGEXTN/notifications/sgwnotify.cpp \
    SGEXTN/primitives/sgxcolourhsla.cpp \
    SGEXTN/primitives/sgxcolourrgba.cpp \
    SGEXTN/primitives/sgxidentifier.cpp \
    SGEXTN/primitives/sgxtimestamp.cpp \
    SGEXTN/primitives/sgxtouchevent.cpp \
    SGEXTN/primitives/sgxvector2.cpp \
    SGEXTN/quickui/sgxquickinterface.cpp \
    SGEXTN/quickui/sgxquickresizer.cpp \
    SGEXTN/quickui/sgxthemecoloursetting.cpp \
    SGEXTN/template/sgwcolourpicker.cpp \
    SGEXTN/template/sgwthemecustomisationpage.cpp \
    SGEXTN/timer/sgxtimer.cpp \
    SGEXTN/userDefinedClasses/sgucentralmanagement.cpp \
    SGEXTN/widgets/noninstantiable/sgwbackground.cpp \
    SGEXTN/widgets/instantiable/sgwblankwidget.cpp \
    SGEXTN/widgets/noninstantiable/sgwbutton.cpp \
    SGEXTN/widgets/instantiable/sgwcolourpickerwidget.cpp \
    SGEXTN/widgets/instantiable/sgwcustomrenderer.cpp \
    SGEXTN/widgets/enums/sgwdefaultfonts.cpp \
    SGEXTN/widgets/enums/sgwhorizontalalignment.cpp \
    SGEXTN/widgets/instantiable/sgwiconbutton.cpp \
    SGEXTN/widgets/instantiable/sgwiconlabel.cpp \
    SGEXTN/widgets/noninstantiable/sgwinput.cpp \
    SGEXTN/widgets/noninstantiable/sgwlabel.cpp \
    SGEXTN/widgets/instantiable/sgwlonginput.cpp \
    SGEXTN/widgets/instantiable/sgwlonglabel.cpp \
    SGEXTN/widgets/instantiable/sgwpagebackground.cpp \
    SGEXTN/widgets/unique/sgwparent.cpp \
    SGEXTN/widgets/unique/sgwroot.cpp \
    SGEXTN/widgets/instantiable/sgwscrollview.cpp \
    SGEXTN/widgets/instantiable/sgwsequentiallonglabel.cpp \
    SGEXTN/widgets/instantiable/sgwsequentialscrollview.cpp \
    SGEXTN/widgets/unique/sgwstatusbar.cpp \
    SGEXTN/widgets/instantiable/sgwtextbutton.cpp \
    SGEXTN/widgets/instantiable/sgwtextinput.cpp \
    SGEXTN/widgets/instantiable/sgwtextlabel.cpp \
    SGEXTN/widgets/instantiable/sgwtouchreceiver.cpp \
    SGEXTN/widgets/enums/sgwtype.cpp \
    SGEXTN/widgets/enums/sgwverticalalignment.cpp \
    SGEXTN/widgets/noninstantiable/sgwwidget.cpp
RESOURCES += SGEXTN/assets.qrc
HEADERS += \
    $$PWD/bypassquickui/sgxresizer.h \
    $$PWD/bypassquickui/sgxthemecolours.h \
    $$PWD/containers/sglarray.h \
    $$PWD/containers/sglcrash.h \
    $$PWD/containers/sglhash.h \
    $$PWD/containers/sgllesserthan.h \
    $$PWD/containers/sglmorethan.h \
    $$PWD/containers/sglpair.h \
    $$PWD/containers/sglprimitivetypechecker.h \
    $$PWD/containers/sglspan.h \
    $$PWD/containers/sgltuple3.h \
    $$PWD/containers/sgltuple4.h \
    $$PWD/containers/sgltuple5.h \
    $$PWD/filesystem/sgxfile.h \
    $$PWD/primitives/sgxchar.h \
    $$PWD/primitives/sgxstring.h \
    $$PWD/quickui/sgwwidgetquickinterface.h \
    $$PWD/quickui/sgxsingcorrectquickinterface.h \
    $$PWD/quickui/sgxtimerquickinterface.h \
    SGEXTN/SingCorrect/sgwsingcorrectcustomisationpage.h \
    SGEXTN/SingCorrect/sgxsingcorrectcore.h \
    SGEXTN/SingCorrect/sgxsingcorrectcustomisation.h \
    SGEXTN/colourbackground/sgxrendercolourbackgroundmaterial.h \
    SGEXTN/colourbackground/sgxrendercolourbackgroundquickuielement.h \
    SGEXTN/colourbackground/sgxrendercolourbackgroundsgwidget.h \
    SGEXTN/colourbackground/sgxrendercolourbackgroundshader.h \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicematerial.h \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicequickuielement.h \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoicesgwidget.h \
    SGEXTN/colourpickerrendering/huechoice/sgxrendercolourpickerhuechoiceshader.h \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicematerial.h \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicequickuielement.h \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoicesgwidget.h \
    SGEXTN/colourpickerrendering/lightnesschoice/sgxrendercolourpickerlightnesschoiceshader.h \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicematerial.h \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicequickuielement.h \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoicesgwidget.h \
    SGEXTN/colourpickerrendering/saturationchoice/sgxrendercolourpickersaturationchoiceshader.h \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicematerial.h \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicequickuielement.h \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoicesgwidget.h \
    SGEXTN/colourpickerrendering/transparencychoice/sgxrendercolourpickertransparencychoiceshader.h \
    SGEXTN/customisation/sgxthemecolourscustomisation.h \
    SGEXTN/filesystem/sgxfilebinutilities.h \
    SGEXTN/filesystem/sgxfiledownloader.h \
    SGEXTN/filesystem/sgxfilesystem.h \
    SGEXTN/filesystem/sgxfileuploader.h \
    SGEXTN/filesystem/sgxfilezip.h \
    SGEXTN/misc/sgxcentral.h \
    SGEXTN/notifications/sgwnotify.h \
    SGEXTN/primitives/sgxcolourhsla.h \
    SGEXTN/primitives/sgxcolourrgba.h \
    SGEXTN/primitives/sgxidentifier.h \
    SGEXTN/primitives/sgxtimestamp.h \
    SGEXTN/primitives/sgxtouchevent.h \
    SGEXTN/primitives/sgxvector2.h \
    SGEXTN/quickui/sgxquickinterface.h \
    SGEXTN/quickui/sgxquickresizer.h \
    SGEXTN/quickui/sgxthemecoloursetting.h \
    SGEXTN/template/sgwcolourpicker.h \
    SGEXTN/template/sgwthemecustomisationpage.h \
    SGEXTN/timer/sgxtimer.h \
    SGEXTN/userDefinedClasses/sgucentralmanagement.h \
    SGEXTN/widgets/noninstantiable/sgwbackground.h \
    SGEXTN/widgets/instantiable/sgwblankwidget.h \
    SGEXTN/widgets/noninstantiable/sgwbutton.h \
    SGEXTN/widgets/instantiable/sgwcolourpickerwidget.h \
    SGEXTN/widgets/instantiable/sgwcustomrenderer.h \
    SGEXTN/widgets/enums/sgwdefaultfonts.h \
    SGEXTN/widgets/enums/sgwhorizontalalignment.h \
    SGEXTN/widgets/instantiable/sgwiconbutton.h \
    SGEXTN/widgets/instantiable/sgwiconlabel.h \
    SGEXTN/widgets/noninstantiable/sgwinput.h \
    SGEXTN/widgets/noninstantiable/sgwlabel.h \
    SGEXTN/widgets/instantiable/sgwlonginput.h \
    SGEXTN/widgets/instantiable/sgwlonglabel.h \
    SGEXTN/widgets/instantiable/sgwpagebackground.h \
    SGEXTN/widgets/unique/sgwparent.h \
    SGEXTN/widgets/unique/sgwroot.h \
    SGEXTN/widgets/instantiable/sgwscrollview.h \
    SGEXTN/widgets/instantiable/sgwsequentiallonglabel.h \
    SGEXTN/widgets/instantiable/sgwsequentialscrollview.h \
    SGEXTN/widgets/unique/sgwstatusbar.h \
    SGEXTN/widgets/instantiable/sgwtextbutton.h \
    SGEXTN/widgets/instantiable/sgwtextinput.h \
    SGEXTN/widgets/instantiable/sgwtextlabel.h \
    SGEXTN/widgets/instantiable/sgwtouchreceiver.h \
    SGEXTN/widgets/enums/sgwtype.h \
    SGEXTN/widgets/enums/sgwverticalalignment.h \
    SGEXTN/widgets/noninstantiable/sgwwidget.h
