name: Windows MSVC build
description: Builds a fully self contained SGEXTN app for Windows AMD64 using MSVC compiler. SGEXTN libraries, Qt libraries, and C++ libraries are packaged with the application executable. This action should be run on a windows-latest GitHub Actions runner. You are strongly encouraged to switch to LLVM-MinGW if there is no particular reason to use MSVC.

inputs:
  app-name:
    required: true
    description: name of your application executable, example my-application
    type: string
  app-version:
    required: true
    description: version number of your application, example 1.0.0
    type: string
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string
  cmake-target-name:
    required: true
    description: name of CMake target for your application executable, this is used to locate the executable, the executable will be renamed after that
    type: string

runs:
  using: "composite"
  steps:
    - name: pull repository
      uses: actions/checkout@v3

    - name: install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: windows
        target: desktop
        dir: ${{github.workspace}}\..
        cache: true
        modules: qtshadertools
        arch: win64_msvc2022_64
        tools: 'tools_vcredist,qt.tools.vcredist_msvc2022_x64 tools_cmake tools_ninja'

    - name: delete unnecessary Qt plugins
      shell: pwsh
      run: |
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_64\plugins\designer"
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_64\plugins\help"
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_64\plugins\sqldrivers"

    - name: build SGEXTN
      shell: cmd
      run: |
        cd ..
        git clone https://github.com/InfinityIntegral/SGEXTN.git
        cd SGEXTN
        $env:PATH = "${{github.workspace}}\..\Qt\Tools\CMake_64\bin;${{github.workspace}}\..\Qt\Tools\Ninja;" + $env:PATH
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_PREFIX_PATH=../../Qt/${{inputs.qt-version}}/msvc2022_64 -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: build application binary
      shell: cmd
      run: |
        $env:PATH = "${{github.workspace}}\..\Qt\Tools\CMake_64\bin;${{github.workspace}}\..\Qt\Tools\Ninja;" + $env:PATH
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_PREFIX_PATH=../../Qt/${{inputs.qt-version}}/msvc2022_64 -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: delete QML tooling
      shell: pwsh
      run: |
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_64\plugins\qmllint"
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_64\plugins\qmlls"
        Remove-Item -Recurse -Force "..\Qt\${{inputs.qt-version}}\msvc2022_64\plugins\qmltooling"

    - name: package app using windowsdeployqt
      shell: pwsh
      run: |
        mkdir ${{github.workspace}}\${{inputs.app-name}}
        Copy-Item -Path "build\${{inputs.cmake-target-name}}.exe" -Destination "${{github.workspace}}\${{inputs.app-name}}\${{inputs.app-name}}.exe"
        Get-ChildItem -Path ..\SGEXTN\build -Filter *.dll -Recurse | ForEach-Object {Copy-Item $_.FullName -Destination ${{github.workspace}}\${{inputs.app-name}} -Force}
        Get-ChildItem -Path build -Filter *.dll -Recurse | ForEach-Object {Copy-Item $_.FullName -Destination ${{github.workspace}}\${{inputs.app-name}} -Force}
        & "..\Qt\${{inputs.qt-version}}\msvc2022_64\bin\windeployqt.exe" ${{github.workspace}}\${{inputs.app-name}}\${{inputs.app-name}}.exe -qmldir=${{github.workspace}}\..\SGEXTN\SG_Widgets\assets --no-translations --no-compiler-runtime --release
        Copy-Item "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\14.44.35112\x64\Microsoft.VC143.CRT\*" ${{inputs.app-name}} -Recurse -Force

    - name: write version file
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        echo. > "${{inputs.app-name}}\version.txt"
        echo using Qt version ${{inputs.qt-version}} >> "${{inputs.app-name}}\version.txt"
        for /f "delims=" %%i in ('cl 2^>^&1 ^| findstr /R /C:".*"') do (
            echo using compiler %%i >> "${{inputs.app-name}}\version.txt"
            goto donecompiler
        )
        :donecompiler
        echo building application ${{inputs.app-name}} version ${{inputs.app-version}} >> "${{inputs.app-name}}\version.txt"

    - name: upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-msvc-${{inputs.app-name}}-${{inputs.app-version}}-build
        path: build

    - name: upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: windows-msvc-${{inputs.app-name}}-${{inputs.app-version}}-binary
        path: ${{inputs.app-name}}
