cmake_minimum_required(VERSION 3.16 FATAL_ERROR)
if(NOT EXISTS "${input}")
    message(FATAL_ERROR "${input} does not exist")
endif()

set(tempVar1 "// BuildLah license check: ${id}")
file(READ "${input}" tempVar2)
string(FIND "${tempVar2}" "${tempVar1}" tempVar3)
if(tempVar3 EQUAL -1)
    string(FIND "${tempVar2}" "// BuildLah license check:" tempVar4)
    if(tempVar4 EQUAL -1)
        message(WARNING "there is no license disclaimer in ${input}")
    else()
        message(WARNING "license disclaimer in ${input} is outdated or mislabeled")
    endif()
endif()
unset(tempVar1)
unset(tempVar2)
unset(tempVar3)
unset(tempVar4)

get_filename_component(tempVar1 "${output}" DIRECTORY)
if(NOT IS_DIRECTORY "${tempVar1}")
    file(MAKE_DIRECTORY "${tempVar1}")
endif()
unset(tempVar1)

file(WRITE "${output}" "")
