cmake_minimum_required(VERSION 3.16 FATAL_ERROR)

foreach(tempVar1 ${input})
    file(GLOB_RECURSE tempVar2 "${tempVar1}/*.h")
    list(APPEND tempVar3 "${tempVar2}")
    file(GLOB_RECURSE tempVar2 "${tempVar1}/*.cpp")
    list(APPEND tempVar3 "${tempVar2}")
    foreach(tempVar4 ${tempVar3})
        file(READ "${tempVar4}" tempVar5)
        string(FIND "${tempVar5}" "// BuildLah license check: ${id}" tempVar6)
        if(tempVar6 EQUAL -1)
            set(testPass false)
            string(FIND "${tempVar5}" "// BuildLah license check:" tempVar7)
            if(tempVar7 EQUAL -1)
                message(WARNING "there is no license disclaimer in ${tempVar4}")
            else()
                message(WARNING "license disclaimer in ${tempVar4} is outdated or mislabelled")
            endif()
            message(STATUS "to pass the license check, ensure that the comment // BuildLah license check: ${id} is present immediately after your license disclaimer")
        endif()
    endforeach()
endforeach()
