include_guard(GLOBAL)

set(BuildLah_internal_v_SGExtnVersion "7.0.0")

file(REMOVE_RECURSE "${CMAKE_BINARY_DIR}/BuildLah_logs")
file(REMOVE_RECURSE "${CMAKE_BINARY_DIR}/BuildLah_install")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/BuildLah_logs")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/BuildLah_install")

function(BuildLah_internal_nf_printToFile)
    if(NOT ARGC EQUAL 2)
        message(FATAL_ERROR "can only print exactly 1 thing to exactly 1 file")
    endif()
    file(APPEND "${CMAKE_BINARY_DIR}/BuildLah_logs/${ARGV0}.txt" "${ARGV1}\n")
endfunction()

function(BuildLah_internal_nf_printToGenericLog)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 thing to generic log")
    endif()
    BuildLah_internal_nf_printToFile("generic_log" "${ARGV0}")
endfunction()

function(BuildLah_internal_nf_printListToGenericLog)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 list to generic log, pls quote lists")
    endif()
    set(RECEIVED_LIST "${ARGV0}")
    string(REPLACE ";" ", " RECEIVED_LIST "${RECEIVED_LIST}")
    set(RECEIVED_LIST "[${RECEIVED_LIST}]")
    BuildLah_internal_nf_printToGenericLog("${RECEIVED_LIST}")
endfunction()

function(BuildLah_internal_nf_printToPlatformInfoLog)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 thing to platform info log")
    endif()
    BuildLah_internal_nf_printToFile("generic_log" "${ARGV0}")
    BuildLah_internal_nf_printToFile("platform_info_log" "${ARGV0}")
endfunction()

function(BuildLah_internal_nf_printToFinalLog)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 thing to final log")
    endif()
    BuildLah_internal_nf_printToFile("generic_log" "${ARGV0}")
    BuildLah_internal_nf_printToFile("final_log" "${ARGV0}")
endfunction()

function(BuildLah_internal_nf_printListToFinalLog)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 list to final log, pls quote lists")
    endif()
    set(RECEIVED_LIST "${ARGV0}")
    string(REPLACE ";" ", " RECEIVED_LIST "${RECEIVED_LIST}")
    set(RECEIVED_LIST "[${RECEIVED_LIST}]")
    BuildLah_internal_nf_printToFinalLog("${RECEIVED_LIST}")
endfunction()

function(BuildLah_internal_nf_printLongListToFinalLog)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 list to final log, pls quote lists")
    endif()
    set(RECEIVED_LIST "")
    foreach(ELEMENT ${ARGV0})
        set(RECEIVED_LIST "${RECEIVED_LIST}- ${ELEMENT}\n")
    endforeach()
    BuildLah_internal_nf_printToFinalLog("${RECEIVED_LIST}")
endfunction()

function(BuildLah_internal_nf_printStatus)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 thing as status message")
    endif()
    BuildLah_internal_nf_printToGenericLog("${ARGV0}")
    message(STATUS "${ARGV0}")
endfunction()

function(BuildLah_internal_nf_printWarning)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 thing as warning message")
    endif()
    BuildLah_internal_nf_printToGenericLog("${ARGV0}")
    message(WARNING "${ARGV0}")
endfunction()

function(BuildLah_internal_nf_printFatalError)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only print exactly 1 thing as fatal error message")
    endif()
    BuildLah_internal_nf_printToGenericLog("${ARGV0}")
    message(FATAL_ERROR "${ARGV0}")
endfunction()

BuildLah_internal_nf_printStatus("")
BuildLah_internal_nf_printStatus("You are using BuildLah from SGEXTN ${BuildLah_internal_v_SGExtnVersion}")
BuildLah_internal_nf_printStatus("see BuildLah_logs folder in build folder for more info")
BuildLah_internal_nf_printStatus("to run the application for testing, install it to build/BuildLah_install first, otherwise it will not work")
BuildLah_internal_nf_printStatus("to distribute the application, get a deployment ready zip file using DeploySia GitHub Actions")
BuildLah_internal_nf_printStatus("to learn about how to use BuildLah, run the function BuildLah_help()")
BuildLah_internal_nf_printStatus("note that BuildLah does not support C++ 20 modules, CMakeLists.txt files in subdirectories, languages other than C++, and spaces in file paths")
BuildLah_internal_nf_printStatus("")

BuildLah_internal_nf_printStatus("source folder: ${CMAKE_SOURCE_DIR}")
BuildLah_internal_nf_printStatus("build folder: ${CMAKE_BINARY_DIR}")
BuildLah_internal_nf_printStatus("")

if(NOT CMAKE_MINIMUM_REQUIRED_VERSION)
    BuildLah_internal_nf_printFatalError("define CMake minimum required version before running find_package for SGEXTN")
elseif(NOT "${CMAKE_MINIMUM_REQUIRED_VERSION}" STREQUAL "3.16")
    BuildLah_internal_nf_printWarning("BuildLah is designed for CMake 3.16, using the behaviour of a different version may cause issues")
endif()

if(NOT CMAKE_PROJECT_NAME)
    BuildLah_internal_nf_printFatalError("declare project before running find_package for SGEXTN")
endif()

if(NOT CMAKE_FIND_NO_INSTALL_PREFIX)
    BuildLah_internal_nf_printFatalError("set global variable CMAKE_FIND_NO_INSTALL_PREFIX to true BEFORE your project call by putting the line set(CMAKE_FIND_NO_INSTALL_PREFIX true) into your CMakeLists.txt above project() but below cmake_minimum_required()")
endif()

if("${CMAKE_BINARY_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")
    BuildLah_internal_nf_printFatalError("do not do in source build")
endif()

BuildLah_internal_nf_printToGenericLog("")
BuildLah_internal_nf_printToGenericLog("configuring BuildLah default settings...")
set(CMAKE_ERROR_DEPRECATED true)
BuildLah_internal_nf_printToGenericLog("stop configure on use of deprecated command: ${CMAKE_ERROR_DEPRECATED}")
set(CMAKE_EXPORT_COMPILE_COMMANDS true)
BuildLah_internal_nf_printToGenericLog("enable compilecommands.json: ${CMAKE_EXPORT_COMPILE_COMMANDS}")
set(CMAKE_FIND_PACKAGE_PREFER_CONFIG true)
BuildLah_internal_nf_printToGenericLog("prefer package supplied config file over CMake supplied config file: ${CMAKE_FIND_PACKAGE_PREFER_CONFIG}")
set(CMAKE_FIND_PACKAGE_RESOLVE_SYMLINKS true)
BuildLah_internal_nf_printToGenericLog("allow find package to replace symlinks with actual path: ${CMAKE_FIND_PACKAGE_RESOLVE_SYMLINKS}")
set(CMAKE_INCLUDE_DIRECTORIES_BEFORE true)
BuildLah_internal_nf_printToGenericLog("prioritise folder headers over system ones: ${CMAKE_INCLUDE_DIRECTORIES_BEFORE}")
set(CMAKE_INSTALL_MESSAGE LAZY)
BuildLah_internal_nf_printToGenericLog("if notify about installation: ${CMAKE_INSTALL_MESSAGE}")
set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/BuildLah_install")
BuildLah_internal_nf_printToGenericLog("default installation location: ${CMAKE_INSTALL_PREFIX}")
set(CMAKE_SKIP_INSTALL_ALL_DEPENDENCY false)
BuildLah_internal_nf_printToGenericLog("install without building first: ${CMAKE_SKIP_INSTALL_ALL_DEPENDENCY}")
set(CMAKE_SUPPRESS_REGENERATION false)
BuildLah_internal_nf_printToGenericLog("build without reconfiguring when CMakeLists.txt change: ${CMAKE_SUPPRESS_REGENERATION}")
set(CMAKE_WARN_DEPRECATED true)
BuildLah_internal_nf_printToGenericLog("send warning when using deprecated feature: ${CMAKE_WARN_DEPRECATED}")
set(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION true)
BuildLah_internal_nf_printToGenericLog("send warning when install commands ignore install location: ${CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION}")

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "lib")
BuildLah_internal_nf_printToGenericLog("static library output location: ${CMAKE_BINARY_DIR}/${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
set(CMAKE_BUILD_WITH_INSTALL_NAME_DIR true)
BuildLah_internal_nf_printToGenericLog("use finalised install_name when building: ${CMAKE_BUILD_WITH_INSTALL_NAME_DIR}")
set(CMAKE_BUILD_WITH_INSTALL_RPATH true)
BuildLah_internal_nf_printToGenericLog("use finalised rpath when building: ${CMAKE_BUILD_WITH_INSTALL_RPATH}")
set(CMAKE_CXX_VISIBILITY_PRESET "hidden")
BuildLah_internal_nf_printToGenericLog("default symbol visibility without BuildLah_exportSymbol_... : ${CMAKE_CXX_VISIBILITY_PRESET}")
set(CMAKE_DISABLE_PRECOMPILE_HEADERS true)
BuildLah_internal_nf_printToGenericLog("disable use of precompiled headers: ${CMAKE_DISABLE_PRECOMPILE_HEADERS}")
set(CMAKE_ENABLE_EXPORTS true)
BuildLah_internal_nf_printToGenericLog("allow linking to symbols marked with BuildLah_exportSymbol_... inside executable: ${CMAKE_ENABLE_EXPORTS}")
set(CMAKE_GNUtoMS false)
BuildLah_internal_nf_printToGenericLog("auto convert MinGW / LLVM-MinGW prebuilt binaries to be compatible with MSVC, which can be inaccurate for C++: ${CMAKE_GNUtoMS}")
set(CMAKE_INCLUDE_CURRENT_DIR false)
BuildLah_internal_nf_printToGenericLog("pollute include paths with source folder: ${CMAKE_INCLUDE_CURRENT_DIR}")
set(CMAKE_INCLUDE_CURRENT_DIR_IN_INTERFACE false)
BuildLah_internal_nf_printToGenericLog("pollute include paths of dependencies with source folder: ${CMAKE_INCLUDE_CURRENT_DIR_IN_INTERFACE}")
set(CMAKE_INSTALL_NAME_DIR "@rpath")
BuildLah_internal_nf_printToGenericLog("install_name (MacOS only): ${CMAKE_INSTALL_NAME_DIR}")
set(CMAKE_INSTALL_REMOVE_ENVIRONMENT_RPATH true)
BuildLah_internal_nf_printToGenericLog("stop temporarily inserted rpath during build from polluting executable: ${CMAKE_INSTALL_REMOVE_ENVIRONMENT_RPATH}")
if(APPLE)
    set(CMAKE_INSTALL_RPATH "@executable_path/../Frameworks;@loader_path/../Frameworks;@executable_path/Frameworks;@loader_path/Frameworks")
elseif(UNIX)
    set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib:$ORIGIN/lib")
endif()
BuildLah_internal_nf_printToGenericLog("rpath: ${CMAKE_INSTALL_RPATH}")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH false)
BuildLah_internal_nf_printToGenericLog("put system paths to 3rd party libraries in executable rpath (just bundle the libraries with the app): ${CMAKE_INSTALL_RPATH_USE_LINK_PATH}")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION false)
BuildLah_internal_nf_printToGenericLog("link time optimisation (extremely slow): ${CMAKE_INTERPROCEDURAL_OPTIMIZATION}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "lib")
BuildLah_internal_nf_printToGenericLog("shared library output location: ${CMAKE_BINARY_DIR}/${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
set(CMAKE_LINK_DEPENDS_NO_SHARED false)
BuildLah_internal_nf_printToGenericLog("skip relinking to shared libraries during rebuilds: ${CMAKE_LINK_DEPENDS_NO_SHARED}")
set(CMAKE_MACOSX_RPATH true)
BuildLah_internal_nf_printToGenericLog("if to use rpath on MacOS: ${CMAKE_MACOSX_RPATH}")
set(CMAKE_NO_BUILTIN_CHRPATH true)
BuildLah_internal_nf_printToGenericLog("properly relink when fixing rpath: ${CMAKE_NO_BUILTIN_CHRPATH}")
set(CMAKE_NO_SYSTEM_FROM_IMPORTED false)
BuildLah_internal_nf_printToGenericLog("complain about issues in 3rd party libraries: ${CMAKE_NO_SYSTEM_FROM_IMPORTED}")
set(CMAKE_POSITION_INDEPENDENT_CODE true)
BuildLah_internal_nf_printToGenericLog("allow build outputs to be moved around: ${CMAKE_POSITION_INDEPENDENT_CODE}")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "bin")
BuildLah_internal_nf_printToGenericLog("executable output location: ${CMAKE_BINARY_DIR}/${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
set(CMAKE_SKIP_INSTALL_ALL_DEPENDENCY false)
BuildLah_internal_nf_printToGenericLog("install without building first: ${CMAKE_SKIP_INSTALL_ALL_DEPENDENCY}")
set(CMAKE_SKIP_INSTALL_RULES false)
BuildLah_internal_nf_printToGenericLog("ignore proper installation: ${CMAKE_SKIP_INSTALL_RULES}")
set(CMAKE_SKIP_INSTALL_RPATH false)
BuildLah_internal_nf_printToGenericLog("ignore rpath when installing: ${CMAKE_SKIP_INSTALL_RPATH}")
set(CMAKE_SKIP_RPATH false)
BuildLah_internal_nf_printToGenericLog("ignore rpath: ${CMAKE_SKIP_RPATH}")
set(CMAKE_VISIBILITY_INLINES_HIDDEN true)
BuildLah_internal_nf_printToGenericLog("hide inline functions: ${CMAKE_VISIBILITY_INLINES_HIDDEN}")

set(CMAKE_CXX_EXTENSIONS false)
BuildLah_internal_nf_printToGenericLog("allow compiler specific extensions: ${CMAKE_CXX_EXTENSIONS}")
set(CMAKE_CXX_STANDARD 20)
BuildLah_internal_nf_printToGenericLog("version of C++ Language Standard used: C++ ${CMAKE_CXX_STANDARD}")
set(CMAKE_CXX_STANDARD_REQUIRED true)
BuildLah_internal_nf_printToGenericLog("refuse to compile if C++ Language Standard is not satisfied: ${CMAKE_CXX_STANDARD_REQUIRED}")

set_property(GLOBAL PROPERTY ALLOW_DUPLICATE_CUSTOM_TARGETS false)
BuildLah_internal_nf_printToGenericLog("allow targets with same name: false")
set_property(GLOBAL PROPERTY GLOBAL_DEPENDS_NO_CYCLES true)
BuildLah_internal_nf_printToGenericLog("ban cyclic dependencies: true")
set_property(GLOBAL PROPERTY REPORT_UNDEFINED_PROPERTIES true)
BuildLah_internal_nf_printToGenericLog("complain about accessing undefined CMake properties: true")

set(CMAKE_XCODE_ATTRIBUTE_EMBEDDED_CONTENT_CONTAINS_SWIFT true)
BuildLah_internal_nf_printToGenericLog("ask XCode to include Swift runtime: ${CMAKE_XCODE_ATTRIBUTE_EMBEDDED_CONTENT_CONTAINS_SWIFT}")
BuildLah_internal_nf_printToGenericLog("")

BuildLah_internal_nf_printToGenericLog("logging platform info")
if(ANDROID)
    BuildLah_internal_nf_printToPlatformInfoLog("building for Android")
elseif(APPLE)
    if(IOS)
        BuildLah_internal_nf_printToPlatformInfoLog("building for iOS")
    else()
        BuildLah_internal_nf_printToPlatformInfoLog("building for non iOS Apple platform, likely MacOS")
    endif()
elseif(UNIX)
    BuildLah_internal_nf_printToPlatformInfoLog("building for non Android and non Apple UNIX platform, likely Linux")
elseif(WIN32)
    if(WINDOWS_STORE)
        BuildLah_internal_nf_printToPlatformInfoLog("building for Microsoft Store / Universal Windows Platform")
    else()
        BuildLah_internal_nf_printToPlatformInfoLog("building for Windows")
    endif()
else()
    BuildLah_internal_nf_printToPlatformInfoLog("building for a system of unknown type")
endif()
BuildLah_internal_nf_printToPlatformInfoLog("building for platform: ${CMAKE_SYSTEM}")
BuildLah_internal_nf_printToPlatformInfoLog("building for CPU architecture: ${CMAKE_SYSTEM_PROCESSOR}")
if(CMAKE_HOST_APPLE)
    BuildLah_internal_nf_printToPlatformInfoLog("running in MacOS")
elseif(CMAKE_HOST_UNIX)
    BuildLah_internal_nf_printToPlatformInfoLog("running in Linux")
elseif(CMAKE_HOST_WIN32)
    BuildLah_internal_nf_printToPlatformInfoLog("running in Windows")
else()
    BuildLah_internal_nf_printToPlatformInfoLog("running in system of unknown type")
endif()
BuildLah_internal_nf_printToPlatformInfoLog("running in: ${CMAKE_HOST_SYSTEM}")
BuildLah_internal_nf_printToPlatformInfoLog("running in system with CPU architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
if(XCODE)
    BuildLah_internal_nf_printToPlatformInfoLog("using XCode version ${XCODE_VERSION}")
elseif(MSVC)
    BuildLah_internal_nf_printToPlatformInfoLog("using MSVC version ${MSVC_VERSION} with toolset version ${MSVC_TOOLSET_VERSION}")
endif()
BuildLah_internal_nf_printToPlatformInfoLog("compile commands generator: ${CMAKE_GENERATOR}")
BuildLah_internal_nf_printToPlatformInfoLog("single type generator build type: ${CMAKE_BUILD_TYPE}")
BuildLah_internal_nf_printToPlatformInfoLog("multi type generator available build types: ${CMAKE_CONFIGURATION_TYPES}")
BuildLah_internal_nf_printToPlatformInfoLog("CMake behaviour version: ${CMAKE_MINIMUM_REQUIRED_VERSION}")
BuildLah_internal_nf_printToPlatformInfoLog("CMake installed version: ${CMAKE_VERSION}")
BuildLah_internal_nf_printToPlatformInfoLog("compiler: ${CMAKE_CXX_COMPILER_ID}, version ${CMAKE_CXX_COMPILER_VERSION}")
BuildLah_internal_nf_printToPlatformInfoLog("sizeof(void*) = ${CMAKE_CXX_SIZEOF_DATA_PTR}")
BuildLah_internal_nf_printToPlatformInfoLog("SGEXTN version: ${BuildLah_internal_v_SGExtnVersion}")
BuildLah_internal_nf_printToPlatformInfoLog("project name: ${CMAKE_PROJECT_NAME}")
BuildLah_internal_nf_printToPlatformInfoLog("project version: ${CMAKE_PROJECT_VERSION}")
BuildLah_internal_nf_printToGenericLog("")

BuildLah_internal_nf_printToGenericLog("logging project info")
BuildLah_internal_nf_printToGenericLog("project name: ${CMAKE_PROJECT_NAME}")
BuildLah_internal_nf_printToGenericLog("project version: ${CMAKE_PROJECT_VERSION}")
BuildLah_internal_nf_printToGenericLog("project website link: ${CMAKE_PROJECT_HOMEPAGE_URL}")
BuildLah_internal_nf_printToGenericLog("project description: ${CMAKE_PROJECT_DESCRIPTION}")
BuildLah_internal_nf_printToGenericLog("")

set(CMAKE_REQUIRED_QUIET true)
include(CheckTypeSize)
set(tempVar1 false)
check_type_size("short" BUILDLAH_SIZEOF_SHORT BUILTIN_TYPES_ONLY LANGUAGE CXX)
if(NOT BUILDLAH_SIZEOF_SHORT EQUAL 2)
    BuildLah_internal_nf_printWarning("sizeof(short) is ${BUILDLAH_SIZEOF_SHORT} instead of 2, this may cause issues")
    set(tempVar1 true)
endif()
check_type_size("int" BUILDLAH_SIZEOF_INT BUILTIN_TYPES_ONLY LANGUAGE CXX)
if(NOT BUILDLAH_SIZEOF_INT EQUAL 4)
    BuildLah_internal_nf_printWarning("sizeof(int) is ${BUILDLAH_SIZEOF_INT} instead of 4, this may cause issues")
    set(tempVar1 true)
endif()
check_type_size("long long" BUILDLAH_SIZEOF_LONG_LONG BUILTIN_TYPES_ONLY LANGUAGE CXX)
if(NOT BUILDLAH_SIZEOF_LONG_LONG EQUAL 8)
    BuildLah_internal_nf_printWarning("sizeof(long long) is ${BUILDLAH_SIZEOF_LONG_LONG} instead of 8, this may cause issues")
    set(tempVar1 true)
endif()
check_type_size("float" BUILDLAH_SIZEOF_FLOAT BUILTIN_TYPES_ONLY LANGUAGE CXX)
if(NOT BUILDLAH_SIZEOF_FLOAT EQUAL 4)
    BuildLah_internal_nf_printWarning("sizeof(float) is ${BUILDLAH_SIZEOF_FLOAT} instead of 4, this may cause issues")
    set(tempVar1 true)
endif()
check_type_size("double" BUILDLAH_SIZEOF_DOUBLE BUILTIN_TYPES_ONLY LANGUAGE CXX)
if(NOT BUILDLAH_SIZEOF_DOUBLE EQUAL 8)
    BuildLah_internal_nf_printWarning("sizeof(double) is ${BUILDLAH_SIZEOF_DOUBLE} instead of 8, this may cause issues")
    set(tempVar1 true)
endif()
set(CMAKE_REQUIRED_QUIET false)
if(NOT tempVar1)
    BuildLah_internal_nf_printToGenericLog("size of short, int, long long, float, double, all match expectations")
endif()
unset(tempVar1)
BuildLah_internal_nf_printToGenericLog("")

define_property(TARGET PROPERTY SingEmbed_embeddedFiles BRIEF_DOCS "files in the SingEmbed virtual file system" FULL_DOCS "list of paths in the SingEmbed virtual file system currently occupied by assets and shaders added from the associated target")
define_property(TARGET PROPERTY SingEmbed_assetSource BRIEF_DOCS "SingEmbed asset files" FULL_DOCS "list of absolute file paths on the physical computer describing the asset files that need to be added to SingEmbed from the associated target")
define_property(TARGET PROPERTY SingEmbed_shaderSource BRIEF_DOCS "SingEmbed shader files" FULL_DOCS "list of absolute file paths on the physical computer describing the shader files that need to be pre compiled and added to SingEmbed from the associated target")

function(BuildLah_help)
    BuildLah_internal_nf_printStatus("list of all BuildLah functions and how to use them:")
    BuildLah_internal_nf_printStatus("")
    BuildLah_internal_nf_printStatus("BuildLah_findDependencies:")
    BuildLah_internal_nf_printStatus("BuildLah_findDependencies(LIBRARY <libraryName> [COMPONENTS <componentNames>...])")
    BuildLah_internal_nf_printStatus("looks for a dependency with the name libraryName, specifying that only its components listed as part of componentNames are wanted")
    BuildLah_internal_nf_printStatus("this is similar to find_package(libraryName REQUIRED COMPONENTS componentNames)")
    BuildLah_internal_nf_printStatus("call this multiple times if you want multiple dependencies")
    BuildLah_internal_nf_printStatus("example usage: BuildLah_findDependencies(LIBRARY SGEXTN COMPONENTS Containers Math CoreText)")
    BuildLah_internal_nf_printStatus("the example attempts to find SGEXTN::Containers, SGEXTN::Math, SGEXTN::CoreText")
    BuildLah_internal_nf_printStatus("")
    BuildLah_internal_nf_printStatus("BuildLah_finaliseProject:")
    BuildLah_internal_nf_printStatus("BuildLah_finaliseProject()")
    BuildLah_internal_nf_printStatus("this must be called exactly once at the end of the CMakeLists.txt")
    BuildLah_internal_nf_printStatus("")
    BuildLah_internal_nf_printStatus("BuildLah_addComponent:")
    BuildLah_internal_nf_printStatus("BuildLah_addComponent(")
    BuildLah_internal_nf_printStatus("NAME <componentName>")
    BuildLah_internal_nf_printStatus("TYPE <componentType>")
    BuildLah_internal_nf_printStatus("ROOT_FOLDER <componentRootFolder>")
    BuildLah_internal_nf_printStatus("[DEPENDENCIES [INTERNAL <internalDependencies>...] [FORWARD <forwardDependencies>...] [FORWARD_ONLY <forwardOnlyDependencies>...]]")
    BuildLah_internal_nf_printStatus("[EXTRA_FOLDERS [HEADER <extraHeaderFolders>...] [SOURCE <extraSourceFolders>...] [ASSETS <extraAssetFolders>...] [SHADERS <extraShaderFolders>...]]")
    BuildLah_internal_nf_printStatus("[DEFINES [INTERNAL <internalDefines>...] [FORWARD <forwardDefines>...] [FORWARD_ONLY <forwardOnlyDefines>...]]")
    BuildLah_internal_nf_printStatus("[COMPILER_FLAGS [INTERNAL <internalCompilerFlags>...] [FORWARD <forwardCompilerFlags>...] [FORWARD_ONLY <forwardOnlyCompilerFlags>...]]")
    BuildLah_internal_nf_printStatus("[LINKER_FLAGS [INTERNAL <internalLinkerFlags>...] [FORWARD <forwardLinkerFlags>...] [FORWARD_ONLY <forwardOnlyLinkerFlags>...]]")
    BuildLah_internal_nf_printStatus(")")
    BuildLah_internal_nf_printStatus("adds a component to the project")
    BuildLah_internal_nf_printStatus("the name of the component, which is the CMake target name, is componentName")
    BuildLah_internal_nf_printStatus("the type of the component depends on componentType")
    BuildLah_internal_nf_printStatus("if componentType is LIBRARY, the component will be built as a shared library if the platform supports shared libraries, and as a static library otherwise")
    BuildLah_internal_nf_printStatus("if componentType is CLI_APP, the component will be built as a command line application which does not show a GUI window")
    BuildLah_internal_nf_printStatus("if componentType is GUI_APP, the component will be built as a GUI app")
    BuildLah_internal_nf_printStatus("the type of the component should match what it would be on Linux, for example a Android app should technically be build using add_library() in classic CMake but it counts as GUI_APP in BuildLah")
    BuildLah_internal_nf_printStatus("componentRootFolder is used as the root folder of the component, hereafter referred to as (root), this should be relative to where your CMakeLists.txt is located")
    BuildLah_internal_nf_printStatus("if the CMakeLists.txt is inside your component root folder, pass . as ROOT_FOLDER")
    BuildLah_internal_nf_printStatus("always specify folders with forward slash as separator and without leading or trailing slashes regardless of platform, this applies to all arguments of this command")
    BuildLah_internal_nf_printStatus("all folders in (root)/include in addition to everything listed in extraHeaderFolders are automatically counted as header folders, this is similar to target_include_directories() with PUBLIC option")
    BuildLah_internal_nf_printStatus("header folders are always forwarded to dependencies of this component, place private headers in a folder (root)/include/private_api instead of restricting them at the CMake level")
    BuildLah_internal_nf_printStatus("all .cpp files in (root)/src in addition to all .cpp files in all folders listed in extraSourceFolders are automatically added as source files, this is similar to target_sources() with PRIVATE option")
    BuildLah_internal_nf_printStatus("all files in (root)/assets in addition to all files in all folders listed in extraAssetFolders are automatically added to the SingEmbed system under the path 💖/projectName/componentName/fileName")
    BuildLah_internal_nf_printStatus("for example, in a project MyApp with component MyComponent having icon.png in its (root)/assets, the file icon.png could be accessed in SingEmbed via the path 💖/MyApp/MyComponent/icon.png")
    BuildLah_internal_nf_printStatus("if you want to keep something in the project folder without adding it to SingEmbed, place it in (root)/misc")
    BuildLah_internal_nf_printStatus("all files in (root)/shaders in addition to all files in all folders listed in extraShaderFolders are compiled and automatically added to the SingEmbed system under the path 💖/projectName/componentName/fileName.sgs")
    BuildLah_internal_nf_printStatus("Note that .sgs, SGEXTN Shader file, is a cross platform shader binary format conceptually similar but technically different and independent from Qt's .qsb")
    BuildLah_internal_nf_printStatus("for example, in a project MyApp with component MyComponent having shader.vert in its (root)/assets, the shader would be compiled and it could be accessed in SingEmbed via the path 💖/MyApp/MyComponent/shader.vert.sgs")
    BuildLah_internal_nf_printStatus("extra folders must all be located within (root) and have their paths specified relative to (root)")
    BuildLah_internal_nf_printStatus("internalDependencies is a list of libraries that this component links to but dependencies of this component do not link to, this is equivalent to target_link_libraries() with PRIVATE option")
    BuildLah_internal_nf_printStatus("forwardDependencies is a list of libraries that both this component and dependencies of this component link to, this is equivalent to target_link_libraries() with PUBLIC option")
    BuildLah_internal_nf_printStatus("forwardOnlyDependencies is a list of libraries that only dependencies of this component but not this component link to, this is equivalent to target_link_lbraries() with INTERFACE option")
    BuildLah_internal_nf_printStatus("internalDefines is a list of preprocessor defines enabled for this component but not the dependencies of this component, this is similar to using target_compile_definitions() with PRIVATE option")
    BuildLah_internal_nf_printStatus("forwardDefines is a list of preprocessor defines enabled for both this component and the dependencies of this component, this is similar to using target_compile_definitions() with PUBLIC option")
    BuildLah_internal_nf_printStatus("forwardOnlyDefines is a list of preprocessor defines enabled for only the dependencies of this component but not this component. this is similar to using target_compile_definitions() with INTERFACE option")
    BuildLah_internal_nf_printStatus("internalCompilerFlags is a list of compiler flags enabled for this component but not the dependencies of this component, this is similar to using target_compile_options() with PRIVATE option")
    BuildLah_internal_nf_printStatus("forwardCompilerFlags is a list of compiler flags enabled for both this component and the dependencies of this component, this is similar to using target_compile_options() with PUBLIC option")
    BuildLah_internal_nf_printStatus("forwardOnlyCompilerFlags is a list of compiler flags enabled for only the dependencies of this component but not this component. this is similar to using target_compile_options() with INTERFACE option")
    BuildLah_internal_nf_printStatus("use generator expressions to write compiler flags as the syntax differs significantly between compilers")
    BuildLah_internal_nf_printStatus("internalLinkerFlags is a list of linker flags enabled for this component but not the dependencies of this component, this is similar to using target_link_options() with PRIVATE option")
    BuildLah_internal_nf_printStatus("forwardLinkerFlags is a list of linker flags enabled for both this component and the dependencies of this component, this is similar to using target_link_options() with PUBLIC option")
    BuildLah_internal_nf_printStatus("forwardOnlyLinkerFlags is a list of linker flags enabled for only the dependencies of this component but not this component. this is similar to using target_link_options() with INTERFACE option")
    BuildLah_internal_nf_printStatus("use generator expressions to write linker flags as the syntax differs significantly between linkers")
    BuildLah_internal_nf_printStatus("BuildLah_addComponent() should be called once per component, each component corresponds to a CMake target")
    BuildLah_internal_nf_printStatus("example usage: BuildLah_addComponent(NAME CoreText TYPE LIBRARY ROOT_FOLDER \"CoreText\" DEPENDENCIES INTERNAL SGEXTN::Containers SGEXTN::Math)")
    BuildLah_internal_nf_printStatus("this example adds a library component CoreText with root folder CoreText and links it to SGEXTN::Containers and SGEXTN::Math without exposing the link to dependencies of CoreText")
    BuildLah_internal_nf_printStatus("")
    BuildLah_internal_nf_printStatus("(end of help menu)")
    BuildLah_internal_nf_printStatus("")
endfunction()

function(BuildLah_findDependencies)
    cmake_parse_arguments(ARG "" "LIBRARY" "COMPONENTS" ${ARGN})
    if(NOT ARG_LIBRARY)
        BuildLah_internal_nf_printFatalError("must specify library to find in BuildLah_findDependencies")
    endif()
    if(DEFINED ARG_UNPARSED_ARGUMENTS)
        BuildLah_internal_nf_printFatalError("unrecognised arguments received by BuildLah_findDependencies, pls use named arguments")
    endif()
    BuildLah_internal_nf_printToGenericLog("looking for ${ARG_LIBRARY}... with following components:")
    BuildLah_internal_nf_printListToGenericLog("${ARG_COMPONENTS}")
    BuildLah_internal_nf_printToGenericLog("custom specified root of ${ARG_LIBRARY}: $ENV{${ARG_LIBRARY}_ROOT}")
    BuildLah_internal_nf_printToGenericLog("if finding the dependency fails, consider specifying ${ARG_LIBRARY}_ROOT as an environmental variable (not CMake variable) in whatever shell that you are running CMake from")
    find_package("${ARG_LIBRARY}" COMPONENTS ${ARG_COMPONENTS})
    if(NOT ${ARG_LIBRARY}_FOUND)
        BuildLah_internal_nf_printFatalError("failed to find ${ARG_LIBRARY}, try setting shell environmental variable ${ARG_LIBRARY}_ROOT")
    endif()
    if(NOT DEFINED ${ARG_LIBRARY}_CONFIG)
        BuildLah_internal_nf_printToGenericLog("${ARG_LIBRARY} is found using a 3rd party config file likely provided by CMake or the operating system")
    else()
        BuildLah_internal_nf_printToGenericLog("config file for ${ARG_LIBRARY} is found at: ${${ARG_LIBRARY}_CONFIG}")
    endif()
    BuildLah_internal_nf_printToGenericLog("")
endfunction()

function(BuildLah_addComponent)
    cmake_parse_arguments("ARG" "" "NAME;TYPE;ROOT_FOLDER" "DEPENDENCIES;EXTRA_FOLDERS;DEFINES;COMPILER_FLAGS;LINKER_FLAGS" ${ARGN})
    if(NOT ARG_NAME)
        BuildLah_internal_nf_printFatalError("must specify component name in BuildLah_addComponent")
    endif()
    if(NOT ARG_TYPE)
        BuildLah_internal_nf_printFatalError("must specify component type in BuildLah_addComponent")
    endif()
    if(NOT ARG_ROOT_FOLDER)
        BuildLah_internal_nf_printFatalError("must specify component root folder in BuildLah_addComponent, use . if the root folder is the one where CMakeLists.txt is")
    endif()
    if(DEFINED ARG_UNPARSED_ARGUMENTS)
        BuildLah_internal_nf_printFatalError("unrecognised arguments received by BuildLah_addComponent, pls use named arguments")
    endif()
    if(DEFINED ARG_DEPENDENCIES)
        cmake_parse_arguments("ARG_DEP" "" "" "INTERNAL;FORWARD;FORWARD_ONLY" ${ARG_DEPENDENCIES})
        if(DEFINED ARG_DEP_UNPARSED_ARGUMENTS)
            BuildLah_internal_nf_printFatalError("unrecognised arguments received by BuildLah_addComponent as dependencies, pls specify INTERNAL / FORWARD / FORWARD_ONLY")
        endif()
    endif()
    if(DEFINED ARG_EXTRA_FOLDERS)
        cmake_parse_arguments("ARG_EXF" "" "" "HEADER;SOURCE;ASSETS;SHADERS" ${ARG_EXTRA_FOLDERS})
        if(DEFINED ARG_EXF_UNPARSED_ARGUMENTS)
            BuildLah_internal_nf_printFatalError("unrecognised arguments received by BuildLah_addComponent as extra folders, pls specify the type of extra folder to be added")
        endif()
    endif()
    if(DEFINED ARG_DEFINES)
        cmake_parse_arguments("ARG_DEF" "" "" "INTERNAL;FORWARD;FORWARD_ONLY" ${ARG_DEFINES})
        if(DEFINED ARG_DEF_UNPARSED_ARGUMENTS)
            BuildLah_internal_nf_printFatalError("unrecognised arguments received by BuildLah_addComponent as preprocessor defines, pls specify INTERNAL / FORWARD / FORWARD_ONLY")
        endif()
    endif()
    if(DEFINED ARG_COMPILER_FLAGS)
        cmake_parse_arguments("ARG_CF" "" "" "INTERNAL;FORWARD;FORWARD_ONLY" ${ARG_COMPILER_FLAGS})
        if(DEFINED ARG_CF_UNPARSED_ARGUMENTS)
            BuildLah_internal_nf_printFatalError("unrecognised arguments received by BuildLah_addComponent as compiler flags, pls specify INTERNAL / FORWARD / FORWARD_ONLY")
        endif()
    endif()
    if(DEFINED ARG_LINKER_FLAGS)
        cmake_parse_arguments("ARG_LF" "" "" "INTERNAL;FORWARD;FORWARD_ONLY" ${ARG_LINKER_FLAGS})
        if(DEFINED ARG_LF_UNPARSED_ARGUMENTS)
            BuildLah_internal_nf_printFatalError("unrecognised arguments received by BuildLah_addComponent as linker flags, pls specify INTERNAL / FORWARD / FORWARD_ONLY")
        endif()
    endif()

    if("${ARG_TYPE}" STREQUAL "LIBRARY")
        get_property(tempVar1 GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS)
        if(tempVar1)
            add_library("${ARG_NAME}" SHARED)
            BuildLah_internal_nf_printToGenericLog("added ${ARG_NAME} as shared library")
            if(APPLE)
                set_property(TARGET "${ARG_NAME}" PROPERTY FRAMEWORK true)
                set_property(TARGET "${ARG_NAME}" PROPERTY FRAMEWORK_VERSION "A")
            endif()
        else()
            BuildLah_internal_nf_printToGenericLog("the platform currently being built for does not support use of shared libraries, using static library instead")
            add_library("${ARG_NAME}" STATIC)
            BuildLah_internal_nf_printToGenericLog("added ${ARG_NAME} as static library")
        endif()
        unset(tempVar1)
    elseif("${ARG_TYPE}" STREQUAL "GUI_APP")
        add_executable("${ARG_NAME}" WIN32 MACOSX_BUNDLE)
        BuildLah_internal_nf_printToGenericLog("added ${ARG_NAME} as GUI application")
    elseif("${ARG_TYPE}" STREQUAL "CLI_APP")
        add_executable("${ARG_NAME}")
        BuildLah_internal_nf_printToGenericLog("added ${ARG_NAME} as CLI application")
    else()
        BuildLah_internal_nf_printFatalError("${ARG_TYPE} is not a valid choice for the type of a component, use LIBRARY / GUI_APP / CLI_APP instead")
    endif()

    if("${ARG_TYPE}" STREQUAL "LIBRARY")
        set_property(TARGET "${ARG_NAME}" PROPERTY COMPILE_PDB_OUTPUT_DIRECTORY "lib")
        set_property(TARGET "${ARG_NAME}" PROPERTY PDB_OUTPUT_DIRECTORY "lib")
    else()
        set_property(TARGET "${ARG_NAME}" PROPERTY COMPILE_PDB_OUTPUT_DIRECTORY "bin")
        set_property(TARGET "${ARG_NAME}" PROPERTY PDB_OUTPUT_DIRECTORY "bin")
    endif()

    set_property(TARGET "${ARG_NAME}" PROPERTY NO_SONAME false)
    set_property(TARGET "${ARG_NAME}" PROPERTY MACHO_COMPATIBILITY_VERSION "${CMAKE_PROJECT_VERSION}")
    set_property(TARGET "${ARG_NAME}" PROPERTY MACHO_CURRENT_VERSION "${CMAKE_PROJECT_VERSION}")
    set_property(TARGET "${ARG_NAME}" PROPERTY SOVERSION "${CMAKE_PROJECT_VERSION}")
    set_property(TARGET "${ARG_NAME}" PROPERTY VERSION "${CMAKE_PROJECT_VERSION}")
    BuildLah_internal_nf_printToGenericLog("version number of ${ARG_NAME}: ${CMAKE_PROJECT_VERSION}")

    if(MSVC)
        target_compile_options("${ARG_NAME}" PRIVATE "/utf-8")
    else()
        target_compile_options("${ARG_NAME}" PRIVATE "-finput-charset=UTF-8")
        target_compile_options("${ARG_NAME}" PRIVATE "-fexec-charset=UTF-8")
    endif()
    BuildLah_internal_nf_printToGenericLog("set ${ARG_NAME} to interpret all string literals as UTF8 encoded")

    file(WRITE "${CMAKE_BINARY_DIR}/BuildLah_SharedLibrarySymbolExporting.h" "#pragma once\n\n#define BUILDLAH_INTERNAL_WindowsSharedLibrarySymbolExport __declspec(dllexport)\n#define BUILDLAH_INTERNAL_WindowsSharedLibrarySymbolImport __declspec(dllimport)\n#define BUILDLAH_INTERNAL_UnixSharedLibrarySymbolVisibility __attribute__((visibility(\"default\")))\n")
    if(MSVC)
        target_compile_options("${ARG_NAME}" PRIVATE /FI"${CMAKE_BINARY_DIR}/BuildLah_SharedLibrarySymbolExporting.h")
    else()
        target_compile_options("${ARG_NAME}" PRIVATE -include "${CMAKE_BINARY_DIR}/BuildLah_SharedLibrarySymbolExporting.h")
    endif()
    BuildLah_internal_nf_printToGenericLog("wrote BuildLah_SharedLibrarySymbolExporting.h in build folder for shared library symbol visibility macros")

    if(WIN32)
        target_compile_definitions("${ARG_NAME}" PRIVATE "BuildLah_${CMAKE_PROJECT_NAME}_${ARG_NAME}=BUILDLAH_INTERNAL_WindowsSharedLibrarySymbolExport")
        target_compile_definitions("${ARG_NAME}" INTERFACE "BuildLah_${CMAKE_PROJECT_NAME}_${ARG_NAME}=BUILDLAH_INTERNAL_WindowsSharedLibrarySymbolImport")
    elseif(UNIX)
        target_compile_definitions("${ARG_NAME}" PUBLIC "BuildLah_${CMAKE_PROJECT_NAME}_${ARG_NAME}=BUILDLAH_INTERNAL_UnixSharedLibrarySymbolVisibility")
    endif()
    BuildLah_internal_nf_printToGenericLog("BuildLah_${CMAKE_PROJECT_NAME}_${ARG_NAME} is defined to be the shared library symbol exporting indicator and can be placed in the definition of classes that should be exported")
    BuildLah_internal_nf_printToGenericLog("for example:")
    BuildLah_internal_nf_printToGenericLog("class BuildLah_${CMAKE_PROJECT_NAME}_${ARG_NAME} PublicExposedClass {};")
    BuildLah_internal_nf_printToGenericLog("")

    set(componentRoot "${CMAKE_SOURCE_DIR}/${ARG_ROOT_FOLDER}")
    if("${ARG_ROOT_FOLDER}" STREQUAL ".")
        set(componentRoot "${CMAKE_SOURCE_DIR}")
    endif()
    if(NOT IS_DIRECTORY "${componentRoot}")
        BuildLah_internal_nf_printFatalError("the root folder ${ARG_ROOT_FOLDER} of the component which resolves to ${componentRoot} is not actually a folder, pls use a path relative to the folder containing your CMakeLists.txt")
    endif()

    if(IS_DIRECTORY "${componentRoot}/include")
        list(APPEND ARG_EXF_HEADER "include")
    endif()
    if(IS_DIRECTORY "${componentRoot}/src")
        list(APPEND ARG_EXF_SOURCE "src")
    endif()
    if(IS_DIRECTORY "${componentRoot}/assets")
        list(APPEND ARG_EXF_ASSETS "assets")
    endif()
    if(IS_DIRECTORY "${componentRoot}/shaders")
        list(APPEND ARG_EXF_SHADERS "shaders")
    endif()

    set(tempVar1 "")
    set(tempVar2 "")
    set(tempVar3 "")
    set(tempVar4 "")
    set(tempVar5 "")
    set(tempVar6 "")
    set(tempVar7 "")
    set(tempVar8 "")
    set(tempVar9 "")
    unset(tempVar1)
    unset(tempVar2)
    unset(tempVar3)
    unset(tempVar4)
    unset(tempVar5)
    unset(tempVar6)
    unset(tempVar7)
    unset(tempVar8)
    unset(tempVar9)

    set(tempVar1 "")
    foreach(tempVar2 ${ARG_EXF_HEADER})
        if(NOT IS_DIRECTORY "${componentRoot}/${tempVar2}")
            BuildLah_internal_nf_printFatalError("header folder ${tempVar2} of component ${ARG_NAME} which resolves to ${componentRoot}/${tempVar2} does not exist")
        endif()
        target_include_directories("${ARG_NAME}" PUBLIC "$<BUILD_INTERFACE:${componentRoot}/${tempVar2}>")
        target_include_directories("${ARG_NAME}" PUBLIC "$<INSTALL_INTERFACE:include>")
        BuildLah_internal_nf_printToGenericLog("added ${tempVar2} as header folder of ${ARG_NAME}")
        file(GLOB_RECURSE tempVar3 CONFIGURE_DEPENDS "${componentRoot}/${tempVar2}/*.h")
        list(APPEND tempVar1 "${tempVar3}")
        foreach(tempVar4 ${tempVar3})
            string(REPLACE "${componentRoot}/" "" tempVar5 "${tempVar4}")
            BuildLah_internal_nf_printToGenericLog("- ${tempVar5}")
        endforeach()
    endforeach()
    unset(tempVar2)
    unset(tempVar3)
    unset(tempVar4)
    unset(tempVar5)

    foreach(tempVar2 ${tempVar1})
        get_filename_component(tempVar3 "${tempVar2}" NAME)
        string(FIND "${tempVar3}" "${CMAKE_PROJECT_NAME}_${ARG_NAME}_" tempVar4)
        if(NOT tempVar4 EQUAL 0)
            BuildLah_internal_nf_printWarning("consider renaming header file ${tempVar3} at path ${tempVar2} to start with ${CMAKE_PROJECT_NAME}_${ARG_NAME}_ to avoid header file name collision in #include directives because header file names cannot be namespaced")
        endif()
    endforeach()
    unset(tempVar2)
    unset(tempVar3)
    unset(tempVar4)
    BuildLah_internal_nf_printToGenericLog("")

    foreach(tempVar2 ${ARG_EXF_SOURCE})
        if(NOT IS_DIRECTORY "${componentRoot}/${tempVar2}")
            BuildLah_internal_nf_printFatalError("source folder ${tempVar2} of component ${ARG_NAME} which resolves to ${componentRoot}/${tempVar2} does not exist")
        endif()
        BuildLah_internal_nf_printToGenericLog("added ${tempVar2} as source folder of ${ARG_NAME}")
        file(GLOB_RECURSE tempVar3 CONFIGURE_DEPENDS "${componentRoot}/${tempVar2}/*.cpp")
        list(APPEND tempVar1 "${tempVar3}")
        foreach(tempVar4 ${tempVar3})
            target_sources("${ARG_NAME}" PRIVATE "${tempVar4}")
            string(REPLACE "${componentRoot}/" "" tempVar5 "${tempVar4}")
            BuildLah_internal_nf_printToGenericLog("- ${tempVar5}")
        endforeach()
    endforeach()
    unset(tempVar2)
    unset(tempVar3)
    unset(tempVar4)
    unset(tempVar5)

    set(tempVar5 "")
    foreach(tempVar2 ${tempVar1})
        string(REPLACE "${componentRoot}/" "" tempVar4 "${tempVar2}")
        set(tempVar3 "${CMAKE_BINARY_DIR}/BuildLah_licenseCheck/${tempVar4}.licensecheck")
        add_custom_command(
            OUTPUT "${tempVar3}"
            COMMAND "${CMAKE_COMMAND}" "-Did=${CMAKE_PROJECT_NAME} ${CMAKE_PROJECT_VERSION}" "-Dinput=${tempVar2}" "-Doutput=${tempVar3}" "-P" "${BuildLah_internal_v_installFolder}/BuildLah_CheckLicense.cmake"
            DEPENDS "${tempVar2}"
            COMMENT "${ARG_NAME} license check: ${tempVar4}"
            VERBATIM
        )
        list(APPEND tempVar5 "${tempVar3}")
    endforeach()
    add_custom_target("BuildLah_internal_t_${ARG_NAME}_licenseCheck" DEPENDS "${tempVar5}")
    add_dependencies("${ARG_NAME}" "BuildLah_internal_t_${ARG_NAME}_licenseCheck")
    unset(tempVar1)
    unset(tempVar2)
    unset(tempVar3)
    unset(tempVar4)
    unset(tempVar5)
    BuildLah_internal_nf_printToGenericLog("")

    # TODO: add SingEmbed for assets (ARG_EXF_ASSETS)
    # TODO: add SingEmbed for shaders (ARG_EXF_SHADERS)
    # TODO: add SingEmbed path collision check

    if(DEFINED ARG_DEP_INTERNAL)
        foreach(tempVar1 ${ARG_DEP_INTERNAL})
            if(NOT TARGET "${tempVar1}")
                BuildLah_internal_nf_printFatalError("internal dependency ${tempVar1} is not valid, ensure that you use BuildLah_findDependencies() to find it first")
            endif()
            target_link_libraries("${ARG_NAME}" PRIVATE "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("linked library ${tempVar1} to ${ARG_NAME} as internal dependency")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_DEP_FORWARD)
        foreach(tempVar1 ${ARG_DEP_FORWARD})
            if(NOT TARGET "${tempVar1}")
                BuildLah_internal_nf_printFatalError("forward dependency ${tempVar1} is not valid, ensure that you use BuildLah_findDependencies() to find it first")
            endif()
            target_link_libraries("${ARG_NAME}" PUBLIC "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("linked library ${tempVar1} to ${ARG_NAME} as forward dependency")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_DEP_FORWARD_ONLY)
        foreach(tempVar1 ${ARG_DEP_FORWARD_ONLY})
            if(NOT TARGET "${tempVar1}")
                BuildLah_internal_nf_printFatalError("forward only dependency ${tempVar1} is not valid, ensure that you use BuildLah_findDependencies() to find it first")
            endif()
            target_link_libraries("${ARG_NAME}" INTERFACE "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("linked library ${tempVar1} to ${ARG_NAME} as forward only dependency")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_DEF_INTERNAL)
        foreach(tempVar1 ${DEFINE_ARG_DEF_INTERNAL})
            target_compile_definitions("${ARG_NAME}" PRIVATE "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added internal preprocessor define ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_DEF_FORWARD)
        foreach(tempVar1 ${DEFINE_ARG_DEF_FORWARD})
            target_compile_definitions("${ARG_NAME}" PUBLIC "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added forward preprocessor define ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_DEF_FORWARD_ONLY)
        foreach(tempVar1 ${DEFINE_ARG_DEF_FORWARD_ONLY})
            target_compile_definitions("${ARG_NAME}" INTERFACE "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added forward only preprocessor define ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_CF_INTERNAL)
        foreach(tempVar1 ${ARG_CF_INTERNAL})
            target_compile_options("${ARG_NAME}" PRIVATE "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added internal compile flag ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_CF_FORWARD)
        foreach(tempVar1 ${ARG_CF_FORWARD})
            target_compile_options("${ARG_NAME}" PUBLIC "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added forward compile flag ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_CF_FORWARD_ONLY)
        foreach(tempVar1 ${ARG_CF_FORWARD_ONLY})
            target_compile_options("${ARG_NAME}" INTERFACE "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added forward only compile flag ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_LF_INTERNAL)
        foreach(tempVar1 ${ARG_LF_INTERNAL})
            target_link_options("${ARG_NAME}" PRIVATE "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added internal linker flag ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_LF_FORWARD)
        foreach(tempVar1 ${ARG_LF_FORWARD})
            target_link_options("${ARG_NAME}" PUBLIC "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added forward linker flag ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)

    if(DEFINED ARG_LF_FORWARD_ONLY)
        foreach(tempVar1 ${ARG_LF_FORWARD_ONLY})
            target_link_options("${ARG_NAME}" INTERFACE "${tempVar1}")
            BuildLah_internal_nf_printToGenericLog("added forward only linker flag ${tempVar1} to ${ARG_NAME}")
        endforeach()
    endif()
    unset(tempVar1)
    BuildLah_internal_nf_printToGenericLog("")

    install( # for Linux only, other platforms will be added later
        TARGETS "${ARG_NAME}"
        EXPORT "${CMAKE_PROJECT_NAME}Targets"
        ARCHIVE DESTINATION "lib"
        LIBRARY DESTINATION "lib"
        RUNTIME DESTINATION "bin"
        FRAMEWORK DESTINATION "lib"
        BUNDLE DESTINATION "bin"
    )
    foreach(tempVar1 ${ARG_EXF_HEADER})
        install(DIRECTORY "${componentRoot}/${tempVar1}/" DESTINATION "include")
    endforeach()
    unset(tempVar1)
    BuildLah_internal_nf_printToGenericLog("installation rules added for ${ARG_NAME}")

    add_dependencies("${ARG_NAME}" "BuildLah_internal_t_finalisationCheck")
    BuildLah_internal_nf_printStatus("setup of ${ARG_NAME} done")
    BuildLah_internal_nf_printToGenericLog("")
endfunction()

function(BuildLah_finaliseProject)
    if(NOT ARGC EQUAL 0)
        BuildLah_internal_nf_printFatalError("BuildLah_finaliseProject does not take any arguments")
    endif()

    install(
        EXPORT "${CMAKE_PROJECT_NAME}Targets"
        DESTINATION "lib/cmake/${CMAKE_PROJECT_NAME}"
        NAMESPACE "${CMAKE_PROJECT_NAME}::"
    )
    include(CMakePackageConfigHelpers)
    configure_package_config_file("cmake/template.cmake.in" "${CMAKE_BINARY_DIR}/${CMAKE_PROJECT_NAME}Config.cmake" INSTALL_DESTINATION "lib/cmake/${CMAKE_PROJECT_NAME}")
    install(FILES "${CMAKE_BINARY_DIR}/${CMAKE_PROJECT_NAME}Config.cmake" DESTINATION "lib/cmake/${CMAKE_PROJECT_NAME}")
    if("${CMAKE_PROJECT_NAME}" STREQUAL "SGEXTN")
        install(FILES "cmake/BuildLah.cmake" DESTINATION "lib/cmake/SGEXTN")
        install(FILES "cmake/BuildLah_CheckLicense.cmake" DESTINATION "lib/cmake/SGEXTN")
        install(FILES "cmake/BuildLah_CheckFinalisation.cmake" DESTINATION "lib/cmake/SGEXTN")
    endif()
    BuildLah_internal_nf_printToGenericLog("done setting install rules for the whole project")

    get_property(tempVar1 DIRECTORY "${CMAKE_SOURCE_DIR}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(tempVar2 ${tempVar1})
        get_property(tempVar3 TARGET "${tempVar2}" PROPERTY NAME)
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY TYPE)
        if("${tempVar4}" STREQUAL "EXECUTABLE")
            BuildLah_internal_nf_printToFinalLog("executable ${tempVar3}:")
        elseif("${tempVar4}" STREQUAL "STATIC_LIBRARY")
            BuildLah_internal_nf_printToFinalLog("static library ${tempVar3}:")
        elseif("${tempVar4}" STREQUAL "SHARED_LIBRARY")
            BuildLah_internal_nf_printToFinalLog("shared library ${tempVar3}:")
        else()
            continue()
        endif()
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY VERSION)
        BuildLah_internal_nf_printToFinalLog("version: ${tempVar4}")
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY COMPILE_DEFINITIONS)
        BuildLah_internal_nf_printToFinalLog("preprocessor defines:")
        BuildLah_internal_nf_printListToFinalLog("${tempVar4}")
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY COMPILE_OPTIONS)
        BuildLah_internal_nf_printToFinalLog("compiler flags:")
        BuildLah_internal_nf_printListToFinalLog("${tempVar4}")
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY LINK_OPTIONS)
        BuildLah_internal_nf_printToFinalLog("linker flags:")
        BuildLah_internal_nf_printListToFinalLog("${tempVar4}")
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY LINK_LIBRARIES)
        BuildLah_internal_nf_printToFinalLog("dependencies:")
        BuildLah_internal_nf_printListToFinalLog("${tempVar4}")
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY INCLUDE_DIRECTORIES)
        BuildLah_internal_nf_printToFinalLog("header folders:")
        BuildLah_internal_nf_printLongListToFinalLog("${tempVar4}")
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY SOURCES)
        BuildLah_internal_nf_printToFinalLog("source files:")
        BuildLah_internal_nf_printLongListToFinalLog("${tempVar4}")
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY SingEmbed_assetSource)
        BuildLah_internal_nf_printToFinalLog("asset files:")
        BuildLah_internal_nf_printLongListToFinalLog("${tempVar4}")
        get_property(tempVar4 TARGET "${tempVar2}" PROPERTY SingEmbed_shaderSource)
        BuildLah_internal_nf_printToFinalLog("shader files:")
        BuildLah_internal_nf_printLongListToFinalLog("${tempVar4}")
        BuildLah_internal_nf_printToFinalLog("")
    endforeach()
    unset(tempVar1)
    unset(tempVar2)
    unset(tempVar3)
    unset(tempVar4)

    file(REMOVE "${CMAKE_BINARY_DIR}/BuildLah_neverFinalise.sg")
    BuildLah_internal_nf_printStatus("project ${CMAKE_PROJECT_NAME} finalised")
    BuildLah_internal_nf_printStatus("")
endfunction()

file(WRITE "${CMAKE_BINARY_DIR}/BuildLah_neverFinalise.sg" "")
add_custom_target(
    "BuildLah_internal_t_finalisationCheck" ALL
    COMMAND "${CMAKE_COMMAND}" "-Dlocation=${CMAKE_BINARY_DIR}/BuildLah_neverFinalise.sg" "-P" "${BuildLah_internal_v_installFolder}/BuildLah_CheckFinalisation.cmake"
    VERBATIM
    BYPRODUCTS "${CMAKE_BINARY_DIR}/BuildLah_neverFinalise.sg"
)
