cmake_minimum_required(VERSION 3.16 FATAL_ERROR)

if(NOT EXISTS "${input}")
    message(FATAL_ERROR "asset ${input} does not exist")
endif()

get_filename_component(tempVar1 "${output}" DIRECTORY)
if(NOT IS_DIRECTORY "${tempVar1}")
    file(MAKE_DIRECTORY "${tempVar1}")
endif()

file(WRITE "${output}" "")
file(APPEND "${output}" "// this file is automatically generated by SingEmbed, pls do not modify it\n")
file(APPEND "${output}" "// asset file path: ${input}\n")
file(APPEND "${output}" "// path in SingEmbed virtual file system: 💖${embed}\n\n")

file(APPEND "${output}" "#include <SGEXTN/SingEmbed/private_api/SingEmbedFileRegistrarInstance.h>\n")
file(APPEND "${output}" "#include <SGEXTN/CoreText/String.h>\n\n")

file(APPEND "${output}" "namespace {\n")
file(APPEND "${output}" "SGEXTN::SingEmbed::SingEmbedFileRegistrarInstance instance(\n")
file(APPEND "${output}" "    \"${embed}\",\n")
file(SIZE "${input}" tempVar1)
file(APPEND "${output}" "    ${tempVar1},\n")

if(tempVar1 EQUAL 0)
    file(APPEND "${output}" "    \"\"\n")
else()
    set(tempVar2 0)
    while(tempVar2 LESS tempVar1)
        file(READ "${input}" tempVar3 OFFSET ${tempVar2} LIMIT 3726 HEX)
        math(EXPR tempVar2 "${tempVar2} + 3726")
        string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "\\\\x\\1" tempVar3 "${tempVar3}")
        file(APPEND "${output}" "    \"${tempVar3}\"\n")
    endwhile()
endif()

file(APPEND "${output}" ");\n")
file(APPEND "${output}" "}\n")
