cmake_minimum_required(VERSION 3.16 FATAL_ERROR)

if(NOT EXISTS "${input}")
    message(FATAL_ERROR "shader ${input} does not exist")
endif()

get_filename_component(tempVar1 "${output}" DIRECTORY)
if(NOT IS_DIRECTORY "${tempVar1}")
    file(MAKE_DIRECTORY "${tempVar1}")
endif()
get_filename_component(tempVar1 "${shaderIm}" DIRECTORY)
if(NOT IS_DIRECTORY "${tempVar1}")
    file(MAKE_DIRECTORY "${tempVar1}")
endif()

set(tempVar1 "compute")
string(FIND "${input}" ".vert.hlsl" tempVar2)
if(NOT ${tempVar2} EQUAL -1)
    set(tempVar1 "vertex")
endif()
string(FIND "${input}" ".frag.hlsl" tempVar2)
if(NOT ${tempVar2} EQUAL -1)
    set(tempVar1 "fragment")
endif()

execute_process(
    COMMAND "${command}" "${input}" "--source" "HLSL" "--dest" "DXBC" "--stage" "${tempVar1}" "--entrypoint" "main" "--output" "${shaderIm}.dxbc"
    RESULT_VARIABLE tempVar3
    OUTPUT_VARIABLE tempVar4 ERROR_VARIABLE tempVar4
)
if(NOT tempVar3 EQUAL 0)
    message(WARNING "${tempVar4}")
    message(FATAL_ERROR "SDL3 ShaderCross return value while compiling DXBC: ${tempVar3}")
endif()

execute_process(
    COMMAND "${command}" "${input}" "--source" "HLSL" "--dest" "DXIL" "--stage" "${tempVar1}" "--entrypoint" "main" "--output" "${shaderIm}.dxil"
    RESULT_VARIABLE tempVar3
    OUTPUT_VARIABLE tempVar4 ERROR_VARIABLE tempVar4
)
if(NOT tempVar3 EQUAL 0)
    message(WARNING "${tempVar4}")
    message(FATAL_ERROR "SDL3 ShaderCross return value while compiling DXIL: ${tempVar3}")
endif()

execute_process(
    COMMAND "${command}" "${input}" "--source" "HLSL" "--dest" "MSL" "--stage" "${tempVar1}" "--entrypoint" "main" "--output" "${shaderIm}.msl"
    RESULT_VARIABLE tempVar3
    OUTPUT_VARIABLE tempVar4 ERROR_VARIABLE tempVar4
)
if(NOT tempVar3 EQUAL 0)
    message(WARNING "${tempVar4}")
    message(FATAL_ERROR "SDL3 ShaderCross return value while compiling MSL: ${tempVar3}")
endif()

execute_process(
    COMMAND "${command}" "${input}" "--source" "HLSL" "--dest" "SPIRV" "--stage" "${tempVar1}" "--entrypoint" "main" "--output" "${shaderIm}.spirv"
    RESULT_VARIABLE tempVar3
    OUTPUT_VARIABLE tempVar4 ERROR_VARIABLE tempVar4
)
if(NOT tempVar3 EQUAL 0)
    message(WARNING "${tempVar4}")
    message(FATAL_ERROR "SDL3 ShaderCross return value while compiling SPIR-V: ${tempVar3}")
endif()

function(toHexadecimal)
    if(NOT ARGC EQUAL 1)
        message(FATAL_ERROR "can only convert exact 1 number")
    endif()
    set(tempVar0 "${${ARGV0}}")
    math(EXPR tempVar0 "${tempVar0}" OUTPUT_FORMAT HEXADECIMAL)
    string(REPLACE "0x" "" tempVar0 "${tempVar0}")
    string(LENGTH "${tempVar0}" tempVar01)
    string(SUBSTRING "00000000${tempVar0}" ${tempVar01} 8 tempVar0)
    set(${ARGV0} "${tempVar0}" PARENT_SCOPE)
    unset(tempVar0)
    unset(tempVar01)
endfunction()

file(WRITE "${shaderIm}.sgs" "5347207368616465720a")
file(SIZE "${shaderIm}.dxbc" tempVar1)
toHexadecimal(tempVar1)
file(APPEND "${shaderIm}.sgs" "${tempVar1}")
file(SIZE "${shaderIm}.dxil" tempVar1)
toHexadecimal(tempVar1)
file(APPEND "${shaderIm}.sgs" "${tempVar1}")
file(SIZE "${shaderIm}.msl" tempVar1)
toHexadecimal(tempVar1)
file(APPEND "${shaderIm}.sgs" "${tempVar1}")
file(SIZE "${shaderIm}.spirv" tempVar1)
toHexadecimal(tempVar1)
file(APPEND "${shaderIm}.sgs" "${tempVar1}")

file(READ "${shaderIm}.dxbc" tempVar1 HEX)
file(APPEND "${shaderIm}.sgs" "${tempVar1}")
file(READ "${shaderIm}.dxil" tempVar1 HEX)
file(APPEND "${shaderIm}.sgs" "${tempVar1}")
file(READ "${shaderIm}.msl" tempVar1 HEX)
file(APPEND "${shaderIm}.sgs" "${tempVar1}")
file(READ "${shaderIm}.spirv" tempVar1 HEX)
file(APPEND "${shaderIm}.sgs" "${tempVar1}")

# (10: "SG shader\n")
# (4: size of DXBC)(4: size of DXIL)(4: size of MSL)(4: size of SPIRV)
# (DXBC)(DXIL)(MSL)(SPIRV)

file(WRITE "${output}" "")
file(APPEND "${output}" "// this file is automatically generated by SingEmbed, pls do not modify it\n")
file(APPEND "${output}" "// shader file path: ${input}\n")
file(APPEND "${output}" "// path in SingEmbed virtual file system: 💖${embed}\n\n")

file(APPEND "${output}" "#include <SGEXTN/SingEmbed/private_api/SingEmbedFileRegistrarInstance.h>\n")
file(APPEND "${output}" "#include <SGEXTN/CoreText/String.h>\n\n")

file(APPEND "${output}" "namespace {\n")
file(APPEND "${output}" "SGEXTN::SingEmbed::SingEmbedFileRegistrarInstance instance(\n")
file(APPEND "${output}" "    \"${embed}\",\n")
file(SIZE "${shaderIm}.sgs" tempVar1)
math(EXPR tempVar1 "${tempVar1} / 2")
file(APPEND "${output}" "    ${tempVar1},\n")

if(tempVar1 EQUAL 0)
    file(APPEND "${output}" "    \"\"\n")
else()
    set(tempVar2 0)
    while(tempVar2 LESS tempVar1)
        file(READ "${shaderIm}.sgs" tempVar3 OFFSET ${tempVar2} LIMIT 7452)
        math(EXPR tempVar2 "${tempVar2} + 7452")
        string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "\\\\x\\1" tempVar3 "${tempVar3}")
        file(APPEND "${output}" "    \"${tempVar3}\"\n")
    endwhile()
endif()

file(APPEND "${output}" ");\n")
file(APPEND "${output}" "}\n")
