name: Linux GCC build
description: Builds a fully self contained SGEXTN app for Linux AMD64 using GCC compiler. SGEXTN libraries and Qt libraries are packaged with the application executable. The target machine must have C++ libraries and glibc installed and with version equal to or newer than the ones found on Ubuntu 22.04. This action should be run on a ubuntu-22.04 GitHub Actions runner.

inputs:
  app-name:
    required: true
    description: name of your application executable, example my-application
    type: string
  app-version:
    required: true
    description: version number of your application, example 1.0.0
    type: string
  qt-version:
    required: true
    description: version of Qt to use, it is preferred that this matches the Qt version you have on your development machine, example 6.10.1
    type: string
  cmake-target-name:
    required: true
    description: name of CMake target for your application executable, this is used to locate the executable, the executable will be renamed after that
    type: string
  user-facing-app-name:
    required: true
    description: application name as how you want the user to see it, this does not need to be a valid file name, example My Application
    type: string
  user-facing-app-version:
    required: true
    description: application version as how you want the user to see it, this does not need to be numerical, example version 1.0.0
    type: string
  app-icon:
    required: true
    description: location of the application icon PNG image as a path in your GitHub repository, example resources/icon.png
    type: string
  user-facing-organisation-name:
    required: true
    description: your organisation name as how you want the user to see it, example 05524F.sg
    type: string
  bundle-id:
    required: true
    description: application bundle identifier, only used on MacOS, iOS, and Android, must be a reverse URL style dot separated list, with every entry containing only lowercase letters and numbers and must start with a lowercase letter, example sg.singapore05524f.myapplication
    type: string
  app-category:
    required: true
    description: one from the list AudioVideo, Audio, Video, Development, Education, Game, Graphics, Network, Office, Science, Settings, System, Utility, only used on Linux, example Utility
    type: string
  licensing:
    required: true
    description: software licensing for your application, you are strongly recommended to use General Public License version 3 (GPLv3), the license file from your GitHub repository will always be copied regardless of this input, example GPLv3
    type: string
  license-file:
    required: true
    description: path to the license file in your GitHub repository, typically LICENSE.txt, example LICENSE.txt
    type: string
  app-description:
    required: true
    description: a short explanatory note to the user what the app is about
    type: string

runs:
  using: "composite"
  steps:
    - name: pull repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
        ref: ${{github.ref}}

    - name: install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{inputs.qt-version}}
        host: linux
        target: desktop
        dir: ${{github.workspace}}/..
        cache: true
        modules: qtshadertools
        tools: 'tools_cmake tools_ninja'

    - name: delete unnecessary Qt plugins
      shell: bash
      run: |
        rm -rf ../Qt/${{inputs.qt-version}}/gcc_64/plugins/designer
        rm -rf ../Qt/${{inputs.qt-version}}/gcc_64/plugins/help
        rm -rf ../Qt/${{inputs.qt-version}}/gcc_64/plugins/printsupport
        rm -rf ../Qt/${{inputs.qt-version}}/gcc_64/plugins/sqldrivers

    - name: build linuxdeployqt
      shell: bash
      run: |
        cd ..
        git clone https://github.com/probonopd/linuxdeployqt.git
        cd linuxdeployqt
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        cp ../../Qt/${{inputs.qt-version}}/gcc_64/libexec/qmlimportscanner tools/linuxdeployqt/qmlimportscanner
        chmod +x tools/linuxdeployqt/qmlimportscanner

    - name: build SGEXTN
      shell: bash
      run: |
        cd ..
        git clone https://github.com/InfinityIntegral/SGEXTN.git
        cd SGEXTN
        mkdir -p build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        cd ..
        cmake --install build --config Release --prefix ../SGEXTN_install

    - name: build application binary
      shell: bash
      run: |
        export PATH="${{github.workspace}}/../SGEXTN_install/lib:${{github.workspace}}/../SGEXTN_install/lib/cmake/SGEXTN:$PATH"
        mkdir -p build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: delete QML tooling
      shell: bash
      run: |
        rm -rf ../Qt/${{inputs.qt-version}}/gcc_64/plugins/qmllint
        rm -rf ../Qt/${{inputs.qt-version}}/gcc_64/plugins/qmlls
        rm -rf ../Qt/${{inputs.qt-version}}/gcc_64/plugins/qmltooling

    - name: package app
      shell: bash
      run: |
        mkdir -p package/${{inputs.app-name}}.AppDir/usr/bin
        mkdir -p package/${{inputs.app-name}}.AppDir/usr/lib
        cp "build/${{inputs.cmake-target-name}}" package/${{inputs.app-name}}.AppDir/usr/bin/${{inputs.app-name}}
        find ../SGEXTN/build -type f -name "*.so*" -exec cp {} package/${{inputs.app-name}}.AppDir/usr/lib/ \;
        find build -type f -name "*.so*" -exec cp {} package/${{inputs.app-name}}.AppDir/usr/lib/ \;
        ../linuxdeployqt/build/tools/linuxdeployqt/linuxdeployqt package/${{inputs.app-name}}.AppDir/usr/bin/${{inputs.app-name}} -qmldir=${{github.workspace}}/../SGEXTN/SG_Widgets/assets -no-translations
        rm -rf package/${{inputs.app-name}}.AppDir/usr/plugins
        mkdir -p package/${{inputs.app-name}}.AppDir/usr/plugins
        cd ${{github.workspace}}/../Qt/${{inputs.qt-version}}/gcc_64/plugins
        find . -type f -name "*.so*" -exec cp --parents {} "${{github.workspace}}/package/${{inputs.app-name}}.AppDir/usr/plugins" \;
        cd ${{github.workspace}}
        mv package/${{inputs.app-name}}.AppDir/usr ${{inputs.app-name}}
        chmod +x ${{inputs.app-name}}/bin/${{inputs.app-name}}

    - name: write version file
      shell: bash
      run: |
        echo "" > ${{inputs.app-name}}/version.txt
        echo "using Qt version ${{inputs.qt-version}}" >> ${{inputs.app-name}}/version.txt
        echo "using compiler $(g++ --version | head -n 1)" >> ${{inputs.app-name}}/version.txt
        echo "building application ${{inputs.app-name}} version ${{inputs.app-version}}" >> ${{inputs.app-name}}/version.txt

    - name: create desktop file
      shell: bash
      run: |
        echo -e "[Desktop Entry]\nType=Application\nName=${{inputs.user-facing-app-name}}\nComment=${{inputs.app-description}}\nIcon=\"@SG_OWNSELF_PATH/icon.png\"\nExec=\"@SG_OWNSELF_PATH/bin/${{inputs.app-name}}\"\nCategories=${{inputs.app-category}}\nPrefersNonDefaultGPU=true" > ${{inputs.app-name}}/${{inputs.bundle-id}}.desktop

    - name: copy over resources
      shell: bash
      run: |
        mkdir -p icons
        cp "${{inputs.app-icon}}" "icons/original.png"
        w=$(identify -format "%w" icons/original.png)
        h=$(identify -format "%h" icons/original.png)
        size=$(( w>h ? w : h ))
        convert icons/original.png -background "rgba(1,1,1,0)" -gravity center -extent ${size}x${size} icons/square.png
        mv icons/square.png ${{inputs.app-name}}/icon.png
        [ -e "${{inputs.license-file}}" ] && cp "${{inputs.license-file}}" "${{inputs.app-name}}/LICENSE.txt"
        [ -e README.md ] && cp README.md "${{inputs.app-name}}/info.md"
        echo -e "This app is built and packaged using SGEXTN automated GitHub Actions workflows\nFor more information, see info.md if it exists\nRun install.sh to install the application properly\nRun uninstall.sh to uninstall the application and delete it from your computer\nOnce the app is installed, do not move it in the file system" > "${{inputs.app-name}}/README.txt"

    - name: create install and uninstall scripts
      shell: bash
      run: |
        cat > "${{inputs.app-name}}/install.sh" <<EOF
        #!/bin/bash
        APP_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
        DESKTOP_SRC="\$APP_DIR/${{inputs.bundle-id}}.desktop"
        DESKTOP_USER="\$HOME/.local/share/applications/${{inputs.bundle-id}}.desktop"
        DESKTOP_SHORTCUT="\$HOME/Desktop/${{inputs.bundle-id}}.desktop"
        TEMP_DESKTOP="\$HOME/.local/share/applications/${{inputs.bundle-id}}.temp"
        sed "s|@SG_OWNSELF_PATH|\$APP_DIR|g" "\$DESKTOP_SRC" > "\$TEMP_DESKTOP"
        mkdir -p "\$HOME/.local/share/applications"
        mkdir -p "\$HOME/Desktop"
        cp "\$TEMP_DESKTOP" "\$DESKTOP_USER"
        chmod +x "\$DESKTOP_USER"
        cp "\$TEMP_DESKTOP" "\$DESKTOP_SHORTCUT"
        chmod +x "\$DESKTOP_SHORTCUT"
        rm "\$TEMP_DESKTOP"
        EOF
        cat > "${{inputs.app-name}}/uninstall.sh" <<EOF
        #!/bin/bash
        APP_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
        DESKTOP_USER="\$HOME/.local/share/applications/${{inputs.bundle-id}}.desktop"
        DESKTOP_SHORTCUT="\$HOME/Desktop/${{inputs.bundle-id}}.desktop"
        rm -f "\$DESKTOP_USER"
        rm -f "\$DESKTOP_SHORTCUT"
        rm -rf "\$APP_DIR"
        EOF

    - name: upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: linux-gcc-${{inputs.app-name}}-${{inputs.app-version}}-build
        path: build

    - name: upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: linux-gcc-${{inputs.app-name}}-${{inputs.app-version}}-binary
        path: ${{inputs.app-name}}

    - name: log info
      if: always()
      shell: bash
      run: |
        echo "logging information -------------------"
        echo ""
        echo "version information:"
        cat ${{inputs.app-name}}/version.txt
        echo ""
        echo "packaged executables:"
        ls ${{inputs.app-name}}/bin
        echo ""
        echo "packaged libraries:"
        ls ${{inputs.app-name}}/lib
